import Lean4Lean.TypeChecker
import Lean4Lean.Verify.NameGenerator
import Lean4Lean.Verify.Typing.Expr

/-!
# Ghost declarations in the checker's local context: definitions

A *ghost* is a free variable whose declaration is present in the local context of a run of the
executable checker but which occurs in none of the run's inputs, in no cached value of its state,
and in no other declaration the run can reach. The frame lemma (`Verify/TypeChecker/Frame.lean`)
says that such a run succeeds, with the same result and final state, in the local context without
the ghosts. See `docs/inductives/STRENGTHENING_PLAN_2026-10-08.md`, component (F).
-/

namespace Lean4Lean.TypeChecker
open Lean hiding Environment Exception
open Kernel

/-- `e` mentions no ghost (`G` is the set of ghosts). Every `FVarsIn` preservation lemma applies. -/
abbrev GF (G : FVarId → Prop) (e : Expr) : Prop := FVarsIn (fun fv => ¬ G fv) e

/-- Every cached *value* of the state is ghost-free, and every ghost has already been generated by
the name generator (so freshly generated free variables are never ghosts). The equivalence
manager and the failure cache only answer booleans and need no condition. -/
structure GFState (G : FVarId → Prop) (s : State) : Prop where
  inferTypeI : ∀ ⦃e r : Expr⦄, s.inferTypeI[e]? = some r → GF G r
  inferTypeC : ∀ ⦃e r : Expr⦄, s.inferTypeC[e]? = some r → GF G r
  whnfCore : ∀ ⦃e r : Expr⦄, s.whnfCoreCache[e]? = some r → GF G r
  whnf : ∀ ⦃e r : Expr⦄, s.whnfCache[e]? = some r → GF G r
  unfold : ∀ ⦃e r : Expr⦄, s.unfold[e]? = some r → GF G r
  reserved : ∀ ⦃fv⦄, G fv → s.ngen.Reserves fv

/-- `c₁` is `c₂` with ghost declarations added to its local context: the two contexts agree
everywhere except the local context, the local contexts agree at every non-ghost, and the
declarations of `c₂` mention no ghost. -/
structure GhostRel (G : FVarId → Prop) (c₁ c₂ : Context) : Prop where
  eq : c₁ = { c₂ with lctx := c₁.lctx }
  find? : ∀ ⦃fv⦄, ¬ G fv → c₁.lctx.find? fv = c₂.lctx.find? fv
  decls : ∀ ⦃fv d⦄, c₂.lctx.find? fv = some d →
    GF G d.type ∧ ∀ ⦃v⦄, d.value? true = some v → GF G v

/-- A computation of the checker is *framed* for the ghosts `G` (with result invariant `R`): a
successful run in a ghost-extended context is the same successful run in the smaller context,
and the result and final state are ghost-free. -/
def M.Framed (G : FVarId → Prop) (x : M α) (R : α → Prop) : Prop :=
  ∀ ⦃c₁ c₂ : Context⦄ ⦃s : State⦄ ⦃a : α⦄ ⦃s' : State⦄, GhostRel G c₁ c₂ → GFState G s →
    x c₁ s = .ok (a, s') → x c₂ s = .ok (a, s') ∧ R a ∧ GFState G s'

/-- The methods of a recursive checker run are framed on ghost-free inputs. -/
structure Methods.Framed (G : FVarId → Prop) (m : Methods) : Prop where
  isDefEqCore : ∀ ⦃t s⦄, GF G t → GF G s → M.Framed G (m.isDefEqCore t s) fun _ => True
  whnfCore : ∀ ⦃e⦄ cheapProj, GF G e → M.Framed G (m.whnfCore e cheapProj) (GF G)
  whnf : ∀ ⦃e⦄, GF G e → M.Framed G (m.whnf e) (GF G)
  inferType : ∀ ⦃e⦄ inferOnly, GF G e → M.Framed G (m.inferType e inferOnly) (GF G)

/-- A `RecM` computation is framed when it is framed for all framed methods. -/
def RecM.Framed (G : FVarId → Prop) (x : RecM α) (R : α → Prop) : Prop :=
  ∀ ⦃m : Methods⦄, m.Framed G → M.Framed G (x m) R

end Lean4Lean.TypeChecker
