import Lean4Lean.TypeChecker
import Lean4Lean.Verify.NameGenerator
import Lean4Lean.Verify.Typing.Expr
import Lean4Lean.Verify.Axioms

/-!
# Ghost declarations in the checker's local context: definitions

A *ghost* is a free variable whose declaration is present in the local context of a run of the
executable checker but which occurs in none of the run's inputs, in no cached value of its state,
and in no other declaration the run can reach. The frame lemma (`Verify/TypeChecker/Frame.lean`)
says that such a run succeeds, with the same result and final state, in the local context without
the ghosts. It is how the constructor telescope certificates are obtained without
strengthening (section 5.3 of the design notes).

Three details of `GhostRel` are forced by the executable:

* The local contexts agree at a non-ghost only up to the declaration *index*
  (`LocalDecl.setIndex 0`): `mkLocalDecl` numbers a new declaration by the size of the context,
  which counts the ghosts, so after opening a binder the two runs hold the same declaration with
  different indices. Nothing the checker computes reads the index (`mkBinding` ignores it, see
  `LocalContext.mkBindingListN_congr_setIndex`).
* Both local-context maps are well formed (`PersistentHashMap.WF`), which is what makes `find?`
  after `mkLocalDecl`/`mkLetDecl` computable in the proofs.
* The environment is ghost-free (`EnvGhostFree`): the checker returns constant types, delta values and
  recursor rule right-hand sides as results; a ghost in one of them would be looked up in the
  local context later.

`M.PreservesGhostRestriction` also records that the name generator only advances (`s.ngen ≤ s'.ngen`), so a caller
can tell that an id generated after the run is fresh for the state before it.

The statement is extensional in the repository's model of the executable: pointer-equality tests
(`PtrEq.lean`) are modelled as pure functions of their arguments, so the two runs agree as
functions of their inputs, not as heap-level traces.
-/

namespace Lean4Lean.TypeChecker
open Lean hiding Environment Exception
open Kernel

/-- `e` mentions no ghost (`G` is the set of ghosts). Every `FVarsIn` preservation lemma applies. -/
abbrev GhostFree (G : FVarId → Prop) (e : Expr) : Prop := FVarsIn (fun fv => ¬ G fv) e

/-- Every cached *value* of the state is ghost-free, and every ghost has already been generated by
the name generator (so freshly generated free variables are never ghosts). The equivalence
manager and the failure cache only answer booleans and need no condition. -/
structure GhostFreeState (G : FVarId → Prop) (s : State) : Prop where
  inferTypeI : ∀ ⦃e r : Expr⦄, s.inferTypeI[e]? = some r → GhostFree G r
  inferTypeC : ∀ ⦃e r : Expr⦄, s.inferTypeC[e]? = some r → GhostFree G r
  whnfCore : ∀ ⦃e r : Expr⦄, s.whnfCoreCache[e]? = some r → GhostFree G r
  whnf : ∀ ⦃e r : Expr⦄, s.whnfCache[e]? = some r → GhostFree G r
  unfold : ∀ ⦃e r : Expr⦄, s.unfold[e]? = some r → GhostFree G r
  reserved : ∀ ⦃fv⦄, G fv → s.ngen.Reserves fv

/-- Every expression of a constant that the checker reads is ghost-free: the type, the delta value,
and the right-hand sides of recursor rules. -/
structure ConstGhostFree (G : FVarId → Prop) (ci : ConstantInfo) : Prop where
  type : GhostFree G ci.type
  deltaValue : ∀ ⦃v⦄, ci.deltaValue? = some v → GhostFree G v
  rules : ∀ ⦃rv : RecursorVal⦄, ci = .recInfo rv → ∀ r ∈ rv.rules, GhostFree G r.rhs

/-- Every constant of the environment is ghost-free. -/
def EnvGhostFree (G : FVarId → Prop) (env : Environment) : Prop :=
  ∀ ⦃n ci⦄, env.find? n = some ci → ConstGhostFree G ci

/-- `c₁` is `c₂` with ghost declarations added to its local context: the two contexts agree
everywhere except the local context, the local contexts agree at every non-ghost (up to the
declaration index), the declarations of `c₂` and the environment mention no ghost, and both local
context maps are well formed. -/
structure GhostRel (G : FVarId → Prop) (c₁ c₂ : Context) : Prop where
  eq : c₁ = { c₂ with lctx := c₁.lctx }
  find? : ∀ ⦃fv⦄, ¬ G fv →
    (c₁.lctx.find? fv).map (·.setIndex 0) = (c₂.lctx.find? fv).map (·.setIndex 0)
  decls : ∀ ⦃fv d⦄, c₂.lctx.find? fv = some d →
    GhostFree G d.type ∧ ∀ ⦃v⦄, d.value? true = some v → GhostFree G v
  wf₁ : c₁.lctx.fvarIdToDecl.WF
  wf₂ : c₂.lctx.fvarIdToDecl.WF
  env : EnvGhostFree G c₂.env

/-- A computation of the checker *preserves the ghost restriction* `G` (with result invariant
`R`): starting from the same ghost-free state, a successful run in a ghost-extended context is the same successful run in the smaller context,
the result and final state are ghost-free, and the name generator has only advanced. -/
def M.PreservesGhostRestriction (G : FVarId → Prop) (x : M α) (R : α → Prop) : Prop :=
  ∀ ⦃c₁ c₂ : Context⦄ ⦃s : State⦄ ⦃a : α⦄ ⦃s' : State⦄, GhostRel G c₁ c₂ → GhostFreeState G s →
    x c₁ s = .ok (a, s') → x c₂ s = .ok (a, s') ∧ R a ∧ GhostFreeState G s' ∧ s.ngen ≤ s'.ngen

/-- The methods of a recursive checker run preserve the ghost restriction on ghost-free inputs. -/
structure Methods.PreservesGhostRestriction (G : FVarId → Prop) (m : Methods) : Prop where
  isDefEqCore : ∀ ⦃t s⦄, GhostFree G t → GhostFree G s →
    M.PreservesGhostRestriction G (m.isDefEqCore t s) fun _ => True
  whnfCore : ∀ ⦃e⦄ cheapProj, GhostFree G e →
    M.PreservesGhostRestriction G (m.whnfCore e cheapProj) (GhostFree G)
  whnf : ∀ ⦃e⦄, GhostFree G e → M.PreservesGhostRestriction G (m.whnf e) (GhostFree G)
  inferType : ∀ ⦃e⦄ inferOnly, GhostFree G e →
    M.PreservesGhostRestriction G (m.inferType e inferOnly) (GhostFree G)

/-- A `RecM` computation preserves the ghost restriction when it does so for all methods that
preserve it. -/
def RecM.PreservesGhostRestriction (G : FVarId → Prop) (x : RecM α) (R : α → Prop) : Prop :=
  ∀ ⦃m : Methods⦄, m.PreservesGhostRestriction G → M.PreservesGhostRestriction G (x m) R

theorem State.exitScope_ngen {saved s : State} : (saved.exitScope mode s).ngen = s.ngen := by
  cases mode <;> rfl

/-- The executable's `withFreshId`, unfolded: run the body on the current name and a state
whose generator has advanced, then leave the scope as the cache mode says (`State.exitScope`). -/
theorem withFreshId_eq {α} (x : Name → M α) (c : Context) (s : State) :
    (withFreshId x : M α) c s =
      (x s.ngen.curr c { s with ngen := s.ngen.next }).map
        fun p => (p.1, s.exitScope c.fuel.cacheMode p.2) := by
  unfold withFreshId instMonadLocalNameGeneratorM
  simp only [bind, ReaderT.bind, StateT.bind, get, getThe, MonadStateOf.get, StateT.get, liftM,
    monadLift, MonadLift.monadLift, Except.bind, pure, Except.pure, ReaderT.pure, StateT.pure,
    modify, modifyGet, MonadStateOf.modifyGet, StateT.modifyGet, mkFreshId, getNGen, setNGen,
    read, readThe, MonadReaderOf.read, ReaderT.read]
  cases c.fuel.cacheMode <;>
  simp only [State.exitScope, bind, ReaderT.bind, StateT.bind, StateT.get, Except.bind, pure,
    Except.pure, ReaderT.pure, StateT.pure, StateT.modifyGet] <;>
  cases x s.ngen.curr c { s with ngen := s.ngen.next } <;> rfl

end Lean4Lean.TypeChecker
