import Lean4Lean.Theory.Typing.Strengthening.Kripke

/-! # The term model: `TermEq`, the least typed equivalence congruence

`TermEq Γ a b` is the least relation on well-typed syntax in a context `Γ` that contains every
`FullStep`, universe-level equivalence (`LEquiv`) and proof irrelevance at a common proposition,
is symmetric and transitive, and is a congruence for application, `λ`, `Π` and projections
(each congruence rule carries a typing premise for its left endpoint). Its carrier is syntax
restricted to typable terms (`termSetoid`); no quotient is taken.

**What this file is and is not.** Transitivity of `TermEq` is a *constructor*, so `TermEq` is an
equivalence by fiat. The content lies in its comparison with the rewriting presentation:
`termEq_iff_join` shows that under `WF` and canonical `Eq`, `TermEq` coincides with `TypedJoin`
(a `FullReduction` join up to `NormalEq`), and `termEq_iff_defeq` that it coincides with
declarative `IsDefEqU`. Both directions are proved from the existing theory: `complete`
(`TermEq.defeq`) is the easy direction and needs no canonical `Eq`; `sound` is
`VEnv.WF.church_rosser` followed by `normal_generated`. `join_trans` proves transitivity of
`TypedJoin` by an honest confluence diagram (`FullReduction.church_rosser`,
`NormalEq.fullReduction`). So this file is a *packaging* of the strengthening problem, not a
solution: the open statement reappears verbatim as `Reflection` (lifted `TermEq` in `Q :: Γ`
descends to `TermEq` in `Γ`), and `reflection_iff_cancel` shows that `Reflection ↔ Cancel`.
`reflection_iff_supportedRepair` gives the equivalent form with `SupportedJoin` (a join whose
paths are `DescendingStep` certificates); `reflection_inhabited` is the inhabited case.

**Opaque constants and self-looping definitions.** The observation models of `Kripke.lean`
failed because a least fixed point of finite observations has nothing to say about a stuck
term (`freshReflection_false`, `extension_not_freshReflection`). The term model keeps stuck
terms apart by name: `opaque_separated` (two rigid constants of a rigid non-structure `Type`,
`Stationary` under `FullReduction`, are unequal when their names differ) and
`loops_separated` (the two self-looping constants of `LoopEnv` are unequal); `loops_iff_opaque`
shows that the looping equations add no closed identifications beyond the opaque declarations;
`variables_separated` separates two variables at `Type`. These statements keep their typing
side conditions: proofs of a common proposition are identified, and function-typed constants
admit eta expansion, so unconditional name separation would be false.

**The `bad_join` obstruction and its repair.** `bad_join_not_descending`: the typed eta step
from `idProp.lift` produces a reduct `t` that is not a lift (its domain annotation mentions the
inserted variable), with `TermEq idProp.lift t` and `NormalEq t t`, so a join between identical
supported endpoints can have an unsupported common reduct and the path cannot consist of
`DescendingStep`s. This refutes descent of an *unchanged* witness, not `Reflection`.
`bad_join_repaired` gives the supported replacement join and the beta repair of the bad eta
reduct (`eta_bad_repair_step`).

**`UninhabitedCancel`.** `Cancel` restricted to binders with no inhabitant in `Γ`; equivalent to
`Cancel` in every well-formed environment (`uninhabitedCancel_iff_cancel`), since the inhabited
case is `Cancel.inhabited`.

Astra's checked round 7 development (`strengthening-context/round7/term-model/TermModel.lean`,
`round7/counterexample/Round7.lean` for `UninhabitedCancel`), adapted with names kept. -/


namespace Lean4Lean.VEnv.StrengtheningTermModel
open VExpr Params

section Generated
variable [Params]

/-- The least typed equivalence congruence generated by full reduction,
level equivalence, and proof irrelevance at a common proposition.
All syntax constructors with expression children have congruence rules.
Reflexivity is restricted to typable syntax. -/
inductive TermEq : List VExpr → VExpr → VExpr → Prop where
  | refl : env.HasType univs Γ a A → TermEq Γ a a
  | step : env.HasType univs Γ a A → FullStep Γ a b → TermEq Γ a b
  | level : env.HasType univs Γ a A → LEquiv univs a b → TermEq Γ a b
  | proofIrrel : env.HasType univs Γ P (.sort .zero) →
      env.HasType univs Γ a P → env.HasType univs Γ b P → TermEq Γ a b
  | symm : TermEq Γ a b → TermEq Γ b a
  | trans : TermEq Γ a b → TermEq Γ b c → TermEq Γ a c
  | app : env.HasType univs Γ (.app f a) T →
      TermEq Γ f g → TermEq Γ a b → TermEq Γ (.app f a) (.app g b)
  | lam : env.HasType univs Γ (.lam A a) T →
      TermEq Γ A B → TermEq (A :: Γ) a b → TermEq Γ (.lam A a) (.lam B b)
  | forallE : env.HasType univs Γ (.forallE A a) T →
      TermEq Γ A B → TermEq (A :: Γ) a b → TermEq Γ (.forallE A a) (.forallE B b)
  | proj : env.HasType univs Γ (.proj S i a) T →
      TermEq Γ a b → TermEq Γ (.proj S i a) (.proj S i b)

/-- Completeness into declarative equality requires no canonical Eq. -/
theorem TermEq.defeq (hΓ : OnCtx Γ (env.IsType univs))
    (H : TermEq Γ a b) : env.IsDefEqU univs Γ a b := by
  induction H with
  | refl h => exact ⟨_, h⟩
  | step h s => exact ⟨_, s.defeq hΓ h⟩
  | level h l => exact l.defeq henv hΓ ⟨_, h⟩
  | proofIrrel hp ha hb => exact ⟨_, .proofIrrel hp ha hb⟩
  | symm _ ih => exact (ih hΓ).symm
  | trans _ _ ih ih' => exact (ih hΓ).trans henv hΓ (ih' hΓ)
  | app ht _ _ ihf iha =>
    obtain ⟨_, _, hf, ha⟩ := ht.app_inv henv.ordered hΓ
    exact ⟨_, .appDF ((ihf hΓ).of_l henv hΓ hf) ((iha hΓ).of_l henv hΓ ha)⟩
  | lam ht _ _ ihA ihb =>
    obtain ⟨⟨_, hA⟩, _, hb⟩ := ht.lam_inv henv.ordered hΓ
    have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA⟩
    exact ⟨_, .lamDF ((ihA hΓ).of_l henv hΓ hA) ((ihb hΓ').of_l henv hΓ' hb)⟩
  | forallE ht _ _ ihA ihb =>
    obtain ⟨⟨_, hA⟩, _, hb⟩ := ht.forallE_inv henv.ordered
    have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA⟩
    exact ⟨_, .forallEDF ((ihA hΓ).of_l henv hΓ hA) ((ihb hΓ').of_l henv hΓ' hb)⟩
  | proj ht _ ih =>
    obtain ⟨info, ls, ps, ix, sm, ft, fl, hi, hl, hu, hp, hn, hf, hft, hm, hc, hg⟩ :=
      ht.proj_inv henv.ordered hΓ
    exact ⟨_, .projDF hi hl hu hp hn hf hft hm
      (hm.trans ((ih hΓ).of_l henv hΓ hm.hasType.2)) hc hg⟩

theorem TermEq.typed (hΓ : OnCtx Γ (env.IsType univs)) (H : TermEq Γ a b) :
    ∃ T, env.HasType univs Γ a T ∧ env.HasType univs Γ b T := by
  obtain ⟨T, h⟩ := H.defeq hΓ
  exact ⟨T, h.hasType⟩

theorem TermEq.reduction (hΓ : OnCtx Γ (env.IsType univs))
    (ha : env.HasType univs Γ a A) (H : FullReduction Γ a b) : TermEq Γ a b := by
  induction H with
  | rfl => exact .refl ha
  | tail before hs ih => exact ih.trans (TermEq.step (FullReduction.hasType hΓ before ha) hs)

/-- Domain conversion for lambda annotations is generated by eta expansion
at the old domain followed by beta, not an additional equation generator. -/
theorem lambda_annotation (hΓ : OnCtx Γ (env.IsType univs))
    (hAB : env.IsDefEq univs Γ A B (.sort u))
    (ha : env.HasType univs (A :: Γ) a T) :
    TermEq Γ (.lam B a) (.lam A a) := by
  have ht : env.HasType univs Γ (.lam B a) (.forallE A T) :=
    (IsDefEq.lamDF hAB ha).hasType.2
  have hstep := FullStep.funEta ht
  have hbeta : FullStep Γ (.lam A (.app (VExpr.lam B a).lift (.bvar 0))) (.lam A a) := by
    simpa only [VExpr.lift, VExpr.liftN, VExpr.inst_liftN_bvar] using
      (FullStep.lam (domain := A) FullStep.rfl
        (FullStep.core (ParRed.beta (A := B.lift) (e₁ := a.liftN 1 1) (e₂ := .bvar 0) ParRed.rfl ParRed.rfl)))
  exact (TermEq.step ht hstep).trans (TermEq.step (hstep.hasType hΓ ht) hbeta)

/-- Every existing normal comparison is generated by these rules.
The well-founded recursion is on its comparison bound, permitting transport
of the smaller body comparison to a convertible domain. -/
theorem normal_generated (hΓ : OnCtx Γ (env.IsType univs))
    (H : NormalEqN η n Γ a b) : TermEq Γ a b := by
  induction n using Nat.strongRecOn generalizing Γ a b η with
  | ind n ih =>
    cases H with
    | refl ht => exact .refl ht
    | sortDF h1 h2 he => exact .level (.sort h1) (.sort he h2)
    | constDF hc h1 h2 hl he => exact .level (.const hc h1 hl) (.const he h2)
    | elimDF ht he =>
      obtain ⟨_, _, _, _, _, _, rfl, rfl, _, _, _, hp, _, _⟩ :=
        ht.hasType.2.elim_inv henv.ordered hΓ
      exact .level ht.hasType.1 (.elim he hp.packedWF)
    | appDF hf hg ha hb hfg hab =>
      exact .app (.app hf ha) (ih _ (by omega) hΓ hfg) (ih _ (by omega) hΓ hab)
    | projDF ht hab => exact .proj ht (ih _ (by omega) hΓ hab)
    | lamDF hA1 hA2 hab =>
      have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA1.hasType.1⟩
      obtain ⟨T, ht⟩ := hab.defeq hΓ'
      exact (lambda_annotation hΓ hA1 ht.hasType.1).trans
        ((TermEq.lam (.lamDF hA1.hasType.1 ht.hasType.1) (.refl hA1.hasType.1)
          (ih _ (by omega) hΓ' hab)).trans
          (lambda_annotation hΓ hA2 ht.hasType.2).symm)
    | forallEDF hA hAB ha hab =>
      have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA.hasType.2⟩
      have ha' := ha.defeqDFC henv.ordered (IsDefEqCtx.succ .zero hA)
      exact .forallE (.forallE hA.hasType.2 ha')
        (ih _ (by omega) hΓ hAB) (ih _ (by omega) hΓ' (hab.defeq_l hΓ hA))
    | etaL ht hb =>
      obtain ⟨_, hp⟩ := ht.isType henv.ordered hΓ
      obtain ⟨⟨_, hA⟩, _⟩ := hp.forallE_inv henv.ordered
      have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA⟩
      obtain ⟨_, hh⟩ := hb.defeq hΓ'
      exact (TermEq.lam (.lamDF hA hh.hasType.1) (.refl hA)
        (ih _ (by omega) hΓ' hb)).trans (TermEq.step ht (.funEta ht)).symm
    | etaR ht hb =>
      obtain ⟨_, hp⟩ := ht.isType henv.ordered hΓ
      obtain ⟨⟨_, hA⟩, _⟩ := hp.forallE_inv henv.ordered
      have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA⟩
      obtain ⟨_, hh⟩ := hb.defeq hΓ'
      exact (TermEq.step ht (.funEta ht)).trans
        (TermEq.lam (.lamDF hA hh.hasType.1) (.refl hA) (ih _ (by omega) hΓ' hb))
    | etaBoth ht ht' hb =>
      obtain ⟨_, hp⟩ := ht.isType henv.ordered hΓ
      obtain ⟨⟨_, hA⟩, _⟩ := hp.forallE_inv henv.ordered
      have hΓ' : OnCtx (_ :: _) (env.IsType univs) := ⟨hΓ, _, hA⟩
      obtain ⟨_, hh⟩ := hb.defeq hΓ'
      exact (TermEq.step ht (.funEta ht)).trans
        ((TermEq.lam (.lamDF hA hh.hasType.1) (.refl hA) (ih _ (by omega) hΓ' hb)).trans
          (TermEq.step ht' (.funEta ht')).symm)
    | proofIrrel hp ha hb => exact .proofIrrel hp ha hb

/-- Universal property: induction gives the least relation closed under exactly
these typed generators and congruences. No soundness/completeness hypothesis on R. -/
theorem TermEq.least (R : List VExpr → VExpr → VExpr → Prop)
    (rrefl : ∀ {Γ a A}, env.HasType univs Γ a A → R Γ a a)
    (rstep : ∀ {Γ a b A}, env.HasType univs Γ a A → FullStep Γ a b → R Γ a b)
    (rlevel : ∀ {Γ a b A}, env.HasType univs Γ a A → LEquiv univs a b → R Γ a b)
    (rproof : ∀ {Γ P a b}, env.HasType univs Γ P (.sort .zero) →
      env.HasType univs Γ a P → env.HasType univs Γ b P → R Γ a b)
    (rsymm : ∀ {Γ a b}, R Γ a b → R Γ b a)
    (rtrans : ∀ {Γ a b c}, R Γ a b → R Γ b c → R Γ a c)
    (rapp : ∀ {Γ f a g b T}, env.HasType univs Γ (.app f a) T →
      R Γ f g → R Γ a b → R Γ (.app f a) (.app g b))
    (rlam : ∀ {Γ A a B b T}, env.HasType univs Γ (.lam A a) T →
      R Γ A B → R (A :: Γ) a b → R Γ (.lam A a) (.lam B b))
    (rpi : ∀ {Γ A a B b T}, env.HasType univs Γ (.forallE A a) T →
      R Γ A B → R (A :: Γ) a b → R Γ (.forallE A a) (.forallE B b))
    (rproj : ∀ {Γ S i a b T}, env.HasType univs Γ (.proj S i a) T →
      R Γ a b → R Γ (.proj S i a) (.proj S i b))
    (H : TermEq Γ a b) : R Γ a b := by
  induction H with
  | refl h => exact rrefl h
  | step h s => exact rstep h s
  | level h l => exact rlevel h l
  | proofIrrel hp ha hb => exact rproof hp ha hb
  | symm _ ih => exact rsymm ih
  | trans _ _ ih ih' => exact rtrans ih ih'
  | app h _ _ ih ih' => exact rapp h ih ih'
  | lam h _ _ ih ih' => exact rlam h ih ih'
  | forallE h _ _ ih ih' => exact rpi h ih ih'
  | proj h _ ih => exact rproj h ih

/-- A syntax carrier restricted to well-typed terms; equality is generated TermEq. -/
def termSetoid (Γ : List VExpr) : Setoid {a : VExpr // VExpr.WF env univs Γ a} where
  r a b := TermEq Γ a.val b.val
  iseqv := ⟨fun a => let ⟨_, h⟩ := a.property; .refl h,
    fun h => h.symm, fun h h' => h.trans h'⟩

/-- Transitivity of the rewriting presentation by the actual confluence diagram.
Join the two reductions from the middle term, then transport both outer normal
comparisons along that join. No call to declarative transitivity or soundness. -/
theorem join_trans (hΓ : OnCtx Γ (env.IsType univs))
    (hab : TypedJoin Γ a b) (hbc : TypedJoin Γ b c) : TypedJoin Γ a c := by
  obtain ⟨A, B, x, y, ha, hb, hx, hy, hxy⟩ := hab
  obtain ⟨_, C, z, w, _, hc, hz, hw, hzw⟩ := hbc
  obtain ⟨y', z', hy', hz', hyz⟩ := FullReduction.church_rosser hΓ hb hy hz
  obtain ⟨x', hx', hxy'⟩ := hxy.fullReduction hΓ hy'
  obtain ⟨w', hw', hwz'⟩ := (hzw.symm hΓ).fullReduction hΓ hz'
  exact ⟨A, C, x', w', ha, hc, hx.trans hx', hw.trans hw',
    hxy'.trans hΓ (hyz.trans hΓ (hwz'.symm hΓ))⟩

/-- A join whose paths come with actual smaller-context step certificates.
Normal comparison and source typing are also certified in the smaller context. -/
def SupportedJoin {Γ Δ : List VExpr} (W : Ctx.LiftN n k Γ Δ) (a b : VExpr) : Prop :=
  ∃ A B x y, env.HasType univs Γ a A ∧ env.HasType univs Γ b B ∧
    ReflTransGen (DescendingStep W) (a.liftN n k) (x.liftN n k) ∧
    ReflTransGen (DescendingStep W) (b.liftN n k) (y.liftN n k) ∧ NormalEq Γ x y

theorem supportedJoin_iff {W : Ctx.LiftN n k Γ Δ} :
    SupportedJoin W a b ↔ TypedJoin Γ a b := by
  constructor
  · rintro ⟨A, B, x, y, ha, hb, hx, hy, hn⟩
    obtain ⟨x', he, hx'⟩ := descending_path_down hx
    obtain rfl : x = x' := VExpr.liftN_inj.mp he
    obtain ⟨y', he, hy'⟩ := descending_path_down hy
    obtain rfl : y = y' := VExpr.liftN_inj.mp he
    exact ⟨A, B, x, y, ha, hb, hx', hy', hn⟩
  · rintro ⟨A, B, x, y, ha, hb, hx, hy, hn⟩
    exact ⟨A, B, x, y, ha, hb, descending_path_up hx, descending_path_up hy, hn⟩

end Generated

section Canonical
variable {E : VEnv} (hE : E.WF) (hEq : E.HasCanonicalEq) {U : Nat}

theorem complete (hΓ : OnCtx Γ (E.IsType U))
    (H : @TermEq (hE.params U) Γ a b) : E.IsDefEqU U Γ a b := by
  letI := hE.params U
  exact H.defeq hΓ

include hEq
/-- Declarative soundness into the generated term model, via Church--Rosser. -/
theorem sound (hΓ : OnCtx Γ (E.IsType U)) (H : E.IsDefEqU U Γ a b) :
    @TermEq (hE.params U) Γ a b := by
  letI := hE.params U
  obtain ⟨T, H⟩ := H
  obtain ⟨x, y, hx, hy, hn⟩ := hE.church_rosser hEq hΓ H
  exact (TermEq.reduction hΓ H.hasType.1 hx).trans
    ((normal_generated hΓ hn.choose_spec).trans
      (TermEq.reduction hΓ H.hasType.2 hy).symm)

theorem termEq_iff_defeq (hΓ : OnCtx Γ (E.IsType U)) :
    @TermEq (hE.params U) Γ a b ↔ E.IsDefEqU U Γ a b :=
  ⟨complete hE hΓ, sound hE hEq hΓ⟩

/-- Church--Rosser for the generated congruence. This proves it has no
additional equations and no missing equations relative to typed joinability. -/
theorem termEq_iff_join (hΓ : OnCtx Γ (E.IsType U)) :
    @TermEq (hE.params U) Γ a b ↔ @TypedJoin (hE.params U) Γ a b := by
  letI := hE.params U
  constructor
  · intro h
    obtain ⟨T, hd⟩ := h.defeq hΓ
    obtain ⟨x, y, hx, hy, hn⟩ := hE.church_rosser hEq hΓ hd
    exact ⟨T, T, x, y, hd.hasType.1, hd.hasType.2, hx, hy, hn⟩
  · intro h
    exact sound hE hEq hΓ (h.defeq hΓ)

theorem weakN (W : Ctx.LiftN n k Γ Δ)
    (hΓ : OnCtx Γ (E.IsType U)) (hΔ : OnCtx Δ (E.IsType U))
    (H : @TermEq (hE.params U) Γ a b) :
    @TermEq (hE.params U) Δ (a.liftN n k) (b.liftN n k) :=
  sound hE hEq hΔ ((complete hE hΓ H).weakN hE.ordered W)

/-- Respects related simultaneous substitutions, including ordinary substitution. -/
theorem substDF (hΓ : OnCtx Γ (E.IsType U)) (hΔ : OnCtx Δ (E.IsType U))
    (hσ : Ctx.SubstEq E U Δ σ τ Γ) (H : @TermEq (hE.params U) Γ a b) :
    @TermEq (hE.params U) Δ (a.subst σ) (b.subst τ) := by
  obtain ⟨T, hd⟩ := complete hE hΓ H
  exact sound hE hEq hΔ ⟨_, hd.substDF hE.ordered hΓ hΔ hσ⟩

/-- The single unproved obligation. Neither endpoint is assumed typable below. -/
def Reflection : Prop :=
  ∀ ⦃U Γ Q a b⦄, OnCtx (Q :: Γ) (E.IsType U) →
    @TermEq (hE.params U) (Q :: Γ) a.lift b.lift →
    @TermEq (hE.params U) Γ a b

theorem reflection_iff_cancel : Reflection hE ↔ Cancel E := by
  constructor
  · intro hr
    apply Cancel.of_front hE
    intro U Γ Q a b hΓ H
    exact complete hE hΓ.1 (hr hΓ (sound hE hEq hΓ H))
  · intro hc U Γ Q a b hΓ H
    exact sound hE hEq hΓ.1 (Front.of_cancel hc hΓ (complete hE hΓ H))

/-- Equivalent formulation of the *same* remaining lemma as replacement
of a whole join by a supported join, including its typing witnesses. -/
theorem reflection_iff_supportedRepair : Reflection hE ↔
    ∀ ⦃U Γ Q a b⦄, OnCtx (Q :: Γ) (E.IsType U) →
      @TypedJoin (hE.params U) (Q :: Γ) a.lift b.lift →
      @SupportedJoin (hE.params U) 1 0 Γ (Q :: Γ) Ctx.LiftN.one a b := by
  constructor
  · intro hr U Γ Q a b hΓ H
    letI := hE.params U
    exact supportedJoin_iff.mpr ((termEq_iff_join hE hEq hΓ.1).mp
      (hr hΓ ((termEq_iff_join hE hEq hΓ).mpr H)))
  · intro hr U Γ Q a b hΓ H
    letI := hE.params U
    exact (termEq_iff_join hE hEq hΓ.1).mpr (supportedJoin_iff.mp
      (hr hΓ ((termEq_iff_join hE hEq hΓ).mp H)))

theorem reflection_inhabited (hΓ : OnCtx (Q :: Γ) (E.IsType U))
    (hq : E.HasType U Γ q Q) (H : @TermEq (hE.params U) (Q :: Γ) a.lift b.lift) :
    @TermEq (hE.params U) Γ a b :=
  sound hE hEq hΓ.1 (IsDefEqU.strengthen_inhabited hE.ordered hq (complete hE hΓ H))

end Canonical

/- The following stationary-head lemmas are reproduced from the checked round-4
opaque development, with their namespace changed. They make the precise meaning
of "stuck" explicit: FullReduction is stationary, including reflexive steps. -/
section
open Params
variable [Params]

def NonFunctionNonProof (Γ : List VExpr) (e : VExpr) : Prop :=
  (∀ A B, ¬ env.HasType univs Γ e (.forallE A B)) ∧
  (∀ P, env.HasType univs Γ P (.sort .zero) → ¬ env.HasType univs Γ e P)

def Stationary (Γ : List VExpr) (e : VExpr) : Prop :=
  ∀ t, FullReduction Γ e t → t = e

theorem normalEq_const_name {Γ : List VExpr} {a b : Name} {lsA lsB : List VLevel}
    (ha : NonFunctionNonProof Γ (.const a lsA))
    (h : NormalEq Γ (.const a lsA) (.const b lsB)) : a = b := by
  obtain ⟨n, hn⟩ := h
  cases hn with
  | refl => rfl
  | constDF => rfl
  | etaBoth ht => exact False.elim (ha.1 _ _ ht)
  | proofIrrel hp ht => exact False.elim (ha.2 _ hp ht)


theorem parRed_const_stable {Γ : List VExpr} {c : Name} {ls : List VLevel}
    (hr : env.Rigid c) {t : VExpr} (h : ParRed Γ (.const c ls) t) :
    t = .const c ls := by
  generalize he : VExpr.const c ls = e at h
  cases h with
  | const => cases he; rfl
  | schema h =>
    have hh := congrArg (fun e : VExpr => e.getAppFnArgs.1) he
    rw [InductiveSignature.CaseSchema.Application.head] at hh
    cases hh
  | extra hp hm =>
    exact False.elim (Params.not_rigid_match (constHeadRigid_iff.mpr hr) hp hm
      (by rw [← he]; rfl))
  | _ => cases he

theorem fullStep_const_stable {Γ : List VExpr} {c : Name} {ls : List VLevel}
    (hr : env.Rigid c) (hreg : recursorData c = none) (hq : c ≠ ``Quot.lift)
    (hf : ∀ A B, ¬ env.HasType univs Γ (.const c ls) (.forallE A B))
    (hs : ∀ family info levels args, env.projections family info →
      ¬ env.HasType univs Γ (.const c ls) (.mkApps (.const family levels) args))
    {t : VExpr} (h : FullStep Γ (.const c ls) t) : t = .const c ls := by
  generalize he : VExpr.const c ls = e at h
  cases h with
  | core h => subst e; exact parRed_const_stable hr h
  | delta h =>
    have hh := congrArg (fun e : VExpr => e.getAppFnArgs.1) he
    rw [InductiveSignature.spine_mkApps_exact _ _ rfl] at hh
    simp only [getAppFnArgs] at hh
    cases hh
    cases h with
    | intro hl => simp [hreg] at hl
  | quotDelta =>
    have hh := congrArg (fun e : VExpr => e.getAppFnArgs.1) he
    rw [InductiveSignature.spine_mkApps_exact _ _ rfl] at hh
    simp only [getAppFnArgs] at hh
    cases hh
    exact False.elim (hq rfl)
  | structEta hp _ _ ht => subst e; exact False.elim (hs _ _ _ _ hp ht)
  | funEta ht => subst e; exact False.elim (hf _ _ ht)
  | _ => cases he

theorem stationary_of_step_stable {Γ : List VExpr} {e : VExpr}
    (hs : ∀ t, FullStep Γ e t → t = e) : Stationary Γ e := by
  intro t h
  induction h with
  | rfl => rfl
  | tail h hstep ih => subst_vars; exact hs _ hstep

end

/-- Confluence separates distinct stationary opaque inhabitants when they are
neither functions nor proofs. The hypotheses concern typing and reduction,
not the definitional inequality being concluded. -/
theorem stationary_constants_not_defeq {env : VEnv} (henv : env.WF)
    (heq : env.HasCanonicalEq) {U : Nat} {Γ : List VExpr}
    {a b : Name} {lsA lsB : List VLevel}
    (hΓ : OnCtx Γ (env.IsType U)) (hne : a ≠ b)
    (ha : @NonFunctionNonProof (henv.params U) Γ (.const a lsA))
    (hsa : @Stationary (henv.params U) Γ (.const a lsA))
    (hsb : @Stationary (henv.params U) Γ (.const b lsB)) :
    ¬ env.IsDefEqU U Γ (.const a lsA) (.const b lsB) := by
  intro ⟨T, H⟩
  letI := henv.params U
  obtain ⟨x, y, hx, hy, hn⟩ := henv.church_rosser heq hΓ H
  cases hsa x hx
  cases hsb y hy
  exact hne (normalEq_const_name ha hn)

theorem opaque_type_exclusions {env : VEnv} (henv : env.WF)
    (hΓ : OnCtx Γ (env.IsType U))
    (hr : env.Rigid I) (hn : ∀ info, ¬ env.projections I info)
    (hI : env.HasType U Γ (.const I lsI) (.sort (.succ .zero)))
    (he : env.HasType U Γ e (.const I lsI)) :
    (∀ A B, ¬ env.HasType U Γ e (.forallE A B)) ∧
    (∀ P, env.HasType U Γ P (.sort .zero) → ¬ env.HasType U Γ e P) ∧
    (∀ family info levels args, env.projections family info →
      ¬ env.HasType U Γ e (.mkApps (.const family levels) args)) := by
  refine ⟨?_, ?_, ?_⟩
  · intro A B hf
    exact IsDefEqU.rigidApp_forallE_inv (args := []) henv hΓ hr hI (he.uniqU henv hΓ hf)
  · intro P hP hp
    have hIP := (he.uniqU henv hΓ hp).of_r henv hΓ hP
    have hl := (hI.uniqU henv hΓ hIP.hasType.1).sort_inv henv hΓ
    have hz := congrFun hl []
    simp [VLevel.eval] at hz
  · intro family info levels args hf hs
    have hne : I ≠ family := by intro hh; subst family; exact hn info hf
    exact IsDefEqU.rigidApp_ne (args := []) henv hΓ hr (henv.projectionRigid hf)
      hne hI (he.uniqU henv hΓ hs)




theorem opaque_stationary {env : VEnv} (henv : env.WF)
    (hΓ : OnCtx Γ (env.IsType U)) {c I : Name} {ls lsI : List VLevel}
    (hc : env.Rigid c) (hq : c ≠ ``Quot.lift)
    (hI : env.Rigid I) (hn : ∀ info, ¬ env.projections I info)
    (htI : env.HasType U Γ (.const I lsI) (.sort (.succ .zero)))
    (htc : env.HasType U Γ (.const c ls) (.const I lsI)) :
    @Stationary (henv.params U) Γ (.const c ls) := by
  letI := henv.params U
  obtain ⟨hf, _, hs⟩ := opaque_type_exclusions henv hΓ hI hn htI htc
  apply stationary_of_step_stable
  intro t ht
  exact fullStep_const_stable hc (henv.registry_contract.rigid c hc).recursor hq hf hs ht

theorem opaque_constants_not_defeq {env : VEnv} (henv : env.WF)
    (heq : env.HasCanonicalEq) (hΓ : OnCtx Γ (env.IsType U))
    {a b I : Name} {lsA lsB lsI : List VLevel}
    (ha : env.Rigid a) (hb : env.Rigid b) (hI : env.Rigid I)
    (hn : ∀ info, ¬ env.projections I info)
    (hne : a ≠ b) (haq : a ≠ ``Quot.lift) (hbq : b ≠ ``Quot.lift)
    (htI : env.HasType U Γ (.const I lsI) (.sort (.succ .zero)))
    (hta : env.HasType U Γ (.const a lsA) (.const I lsI))
    (htb : env.HasType U Γ (.const b lsB) (.const I lsI)) :
    ¬ env.IsDefEqU U Γ (.const a lsA) (.const b lsB) := by
  obtain ⟨hf, hp, _⟩ := opaque_type_exclusions henv hΓ hI hn htI hta
  exact stationary_constants_not_defeq henv heq hΓ hne ⟨hf, hp⟩
    (opaque_stationary henv hΓ ha haq hI hn htI hta)
    (opaque_stationary henv hΓ hb hbq hI hn htI htb)


/-- Opaque non-proof values in an opaque non-structure Type are distinguished by name. -/
theorem opaque_separated {E : VEnv} (hE : E.WF) (hEq : E.HasCanonicalEq)
    (hΓ : OnCtx Γ (E.IsType U)) {a b I : Name} {lsA lsB lsI : List VLevel}
    (ha : E.Rigid a) (hb : E.Rigid b) (hI : E.Rigid I)
    (hn : ∀ info, ¬ E.projections I info)
    (hne : a ≠ b) (haq : a ≠ ``Quot.lift) (hbq : b ≠ ``Quot.lift)
    (htI : E.HasType U Γ (.const I lsI) (.sort (.succ .zero)))
    (hta : E.HasType U Γ (.const a lsA) (.const I lsI))
    (htb : E.HasType U Γ (.const b lsB) (.const I lsI)) :
    ¬ @TermEq (hE.params U) Γ (.const a lsA) (.const b lsB) :=
  fun h => opaque_constants_not_defeq hE hEq hΓ ha hb hI hn hne haq hbq htI hta htb
    (complete hE hΓ h)

open StrengtheningKripke
theorem loops_separated {E E₁ E' : VEnv} {L₁ L₂ : Name}
    (hE : E.WF) (H : LoopEnv E L₁ L₂ E₁ E')
    (hne : L₁ ≠ L₂) (h₁ : E.constants L₁ = none) (h₂ : E.constants L₂ = none) :
    ¬ @TermEq ((H.wf' hE hne).params 0) [] (.const L₁ []) (.const L₂ []) :=
  fun h => H.not_defeq hE hne h₁ h₂ (complete (Γ := []) (H.wf' hE hne) trivial h)

/-- Adding the two self-loop equations changes no closed term-model equations.
Removing them gives precisely the same model equations for the opaque declarations. -/
theorem loops_iff_opaque {E E₁ E' : VEnv} {L₁ L₂ : Name}
    (hE : E.WF) (hEq : E.HasCanonicalEq) (H : LoopEnv E L₁ L₂ E₁ E')
    (hne : L₁ ≠ L₂) {a b : VExpr} :
    @TermEq ((H.wf' hE hne).params U) [] a b ↔
    @TermEq ((H.wf₁ hE).params U) [] a b := by
  constructor
  · intro h
    obtain ⟨T, hd⟩ := complete (Γ := []) (H.wf' hE hne) trivial h
    exact sound (H.wf₁ hE) (hEq.mono H.le₁) trivial ⟨T, H.toAxioms hne hd⟩
  · intro h
    obtain ⟨T, hd⟩ := complete (Γ := []) (H.wf₁ hE) trivial h
    exact sound (H.wf' hE hne) (H.canonicalEq hEq) trivial ⟨T, hd.mono H.le'⟩

/-- Variables at Type are separated, without any observation interpretation. -/
theorem variables_separated {E : VEnv} (hE : E.WF) (U : Nat) :
    ¬ @TermEq (hE.params U) [.sort (.succ .zero), .sort (.succ .zero)] (.bvar 0) (.bvar 1) := by
  have hΓ : OnCtx [VExpr.sort (.succ .zero), .sort (.succ .zero)] (E.IsType U) :=
    ⟨⟨trivial, _, .sort trivial⟩, _, .sort trivial⟩
  intro h
  have h1 := (complete hE hΓ h).instN hE.ordered Ctx.InstN.zero
    (StrengtheningObstructions.bodySort_typed (env := E) (U := U) (Γ := [.sort (.succ .zero)]))
  have h2 := h1.instN hE.ordered Ctx.InstN.zero
    (StrengtheningObstructions.bodyPi_typed (env := E) (U := U) (Γ := []))
  have h3 : E.IsDefEqU U [] (.sort .zero) (.forallE (.sort .zero) (.sort .zero)) := by
    simpa [StrengtheningObstructions.bodySort, StrengtheningObstructions.bodyPi,
      VExpr.inst, VExpr.instVar] using h2
  exact IsDefEqU.sort_forallE_inv hE (show OnCtx [] (E.IsType U) from trivial) h3

section Obstruction
variable [Params]
open StrengtheningObstructions

/-- A fully typed join between supported endpoints can have an unsupported
common reduct. That very path cannot admit DescendingStep certificates.
This refutes witness-wise descent, not Reflection or replacement of the join. -/
theorem bad_join_not_descending :
    ∃ t A, env.HasType univs [.sort .zero] idProp.lift A ∧
      FullStep [.sort .zero] idProp.lift t ∧
      TermEq [.sort .zero] idProp.lift t ∧
      NormalEq [.sort .zero] t t ∧ ¬ t.Skips 1 0 ∧
      ¬ ReflTransGen (DescendingStep (Ctx.LiftN.one (A := .sort .zero) (Γ := [])))
        idProp.lift t := by
  have hΓ : OnCtx [VExpr.sort .zero] (env.IsType univs) := ⟨trivial, _, .sort trivial⟩
  have ht : env.HasType univs [] idProp (.forallE (.sort .zero) (.sort .zero)) :=
    .lamDF (HasType.sort trivial) (.bvar .zero)
  have ht' := ht.weakN henv.ordered (Ctx.LiftN.one (A := .sort .zero))
  obtain ⟨t, hs, hns⟩ := eta_does_not_preserve_support
  refine ⟨t, _, ht', hs, .step ht' hs, .refl (hs.hasType hΓ ht'), hns, ?_⟩
  intro hd
  obtain ⟨b, rfl, _⟩ := descending_path_down hd
  exact hns VExpr.Skips.liftN

/-- The same eta obstruction has a supported replacement in this model. -/
theorem bad_join_repaired :
    SupportedJoin (Ctx.LiftN.one (A := .sort .zero) (Γ := [])) idProp idProp ∧
      FullStep [.sort .zero] etaBad etaGood.lift := by
  have ht : env.HasType univs [] idProp (.forallE (.sort .zero) (.sort .zero)) :=
    .lamDF (HasType.sort trivial) (.bvar .zero)
  have hs := eta_good_step
  refine ⟨supportedJoin_iff.mpr ⟨_, _, etaGood, etaGood, ht, ht,
    ReflTransGen.tail .rfl hs, ReflTransGen.tail .rfl hs,
    .refl (hs.hasType trivial ht)⟩, eta_bad_repair_step⟩

end Obstruction
/-! ## `Cancel` restricted to uninhabited binders -/

/-- `Cancel` for binders `Q` with no inhabitant in `Γ`. The inhabited case of `Cancel` is
substitution (`Cancel.inhabited`), so this is the whole problem
(`uninhabitedCancel_iff_cancel`). -/
def UninhabitedCancel (env : VEnv) : Prop :=
  ∀ ⦃U Γ Q a b⦄, OnCtx Γ (env.IsType U) →
    (∀ q, ¬ env.HasType U Γ q Q) →
    env.IsDefEqU U Γ (.lam Q a.lift) (.lam Q b.lift) →
    env.IsDefEqU U Γ a b

theorem uninhabitedCancel_iff_cancel {env : VEnv} (henv : env.WF) :
    UninhabitedCancel env ↔ Cancel env := by
  constructor
  · intro H U Γ Q a b hΓ hab
    classical
    by_cases hq : ∃ q, env.HasType U Γ q Q
    · obtain ⟨q, hq⟩ := hq
      exact Cancel.inhabited henv hΓ hq hab
    · exact H hΓ (by simpa using hq) hab
  · intro H U Γ Q a b hΓ _ hab
    exact H hΓ hab

end Lean4Lean.VEnv.StrengtheningTermModel

