import Lean4Lean.Replay
import Lean4Lean.Verify.CanonicalEq

/-!
# Soundness of the replay driver

`Lean4Lean.Replay.replayCore` (in `Lean4Lean/Replay.lean`) is the driver behind
`lake exe lean4lean`: it walks the constants of a source environment in dependency order,
rebuilds a `Declaration` from each `ConstantInfo`, and adds it with the verified kernel
`Lean4Lean.addDecl`; it then compares the constructors and recursors generated by the kernel with
the source's, and finally checks that every replayed constant is present in the environment it
built and agrees with the source constant.

The core carries its own soundness evidence in its types: its state records that the current
environment is reached from the start environment by successful `addDecl` calls (`Replayed`),
and its result (`ReplayResult`) records the final agreement check. So the theorems below are about
*every* `ReplayResult`, and apply to the pure instance `replayPure`/`replayFresh` as well as to the
IO instance the executable runs (`replay`, `replayFromFresh`, `replayFromImports`), without
unfolding the dependency walk (a `partial def`).

Agreement is up to `==` on `ConstantInfo`: the derived equality, which compares expressions with
`Expr.eqv`, so it ignores binder names and binder annotations. This is the same comparison the
driver has always used for constructors and recursors.

The per-declaration theorems are stated for the default fuel `{}`, which is also the executable's
configuration when no `--config` flag is given. The walk lemma `Replayed.foldlM` holds for any
fuel.
-/

namespace Lean4Lean

open Lean hiding Environment Exception
open Kernel

/-! ### Replays -/

/-- The prelude's `Eq`, `Eq.refl` and `Eq.rec` are declared in `env` with their production
types. -/
def HasPreludeEq (env : Environment) : Prop :=
  ∃ eqInfo reflInfo recInfo,
    env.find? ``Eq = some eqInfo ∧ IsPreludeEq eqInfo ∧
    env.find? ``Eq.refl = some reflInfo ∧ IsPreludeEqRefl reflInfo ∧
    env.find? ``Eq.rec = some recInfo ∧ IsPreludeEqRec recInfo

/-- A replay: the declarations `ds` added one after another by the checked `addDecl`, from
`env` to `env'`. A `quotDecl` step records that the prelude's `Eq` is already present
(`HasPreludeEq`): `quotDecl` is modelled by an abstract rule that types `Quot.lift` against
`Eq`, so before `Eq` exists it has no model (and the executable rejects it, `checkEqType`). -/
inductive AddDeclChain : Environment → List Declaration → Environment → Prop
  | nil (env : Environment) : AddDeclChain env [] env
  | cons {env env₁ env₂ : Environment} {d : Declaration} {ds : List Declaration} :
    addDecl env d (check := true) (fuel := {}) = .ok env₁ →
    (d = .quotDecl → HasPreludeEq env) →
    AddDeclChain env₁ ds env₂ → AddDeclChain env (d :: ds) env₂

/-- Every step of a replay preserves `VEnvs.WF`. -/
theorem AddDeclChain.WF {env env' : Environment} {ds : List Declaration}
    (H : AddDeclChain env ds env') {ves : VEnvs} (wf : ves.WF env) :
    ∃ ves' : VEnvs, ves'.WF env' ∧ ∀ safety, ves.venv safety ≤ ves'.venv safety := by
  induction H generalizing ves with
  | nil => exact ⟨ves, wf, fun _ => VEnv.LE.rfl⟩
  | @cons env env₁ env₂ d ds hadd hquot _ ih =>
    have hq : d = .quotDecl → ∀ safety, (ves.venv safety).QuotReady := fun hd safety => by
      obtain ⟨_, _, _, hEq, hEqP, hRefl, hReflP, hRec, hRecP⟩ := hquot hd
      exact (wf.toWFCore.canonicalEq_constants hEq hEqP hRefl hReflP hRec hRecP safety).1
    obtain ⟨ves₁, wf₁, hle₁, hcert⟩ :=
      addDecl.WF_quotReadyAt wf.toWFCore wf.ctorCert d hq _ hadd
    obtain ⟨ves₂, wf₂, hle₂⟩ := ih ⟨wf₁, hcert wf.ctorCert⟩
    exact ⟨ves₂, wf₂, fun safety => (hle₁ safety).trans (hle₂ safety)⟩

/-- **Replay from the empty environment.** Every environment reached by a replay from the
empty environment the executable starts from (`lake exe lean4lean --fresh`) is modelled by
well-formed abstract environments. -/
theorem AddDeclChain.WF_empty {m : Name} {s : Bool} {ds : List Declaration} {env : Environment}
    (H : AddDeclChain (Kernel.Environment.empty m s) ds env) :
    ∃ ves : VEnvs, ves.WF env :=
  let ⟨ves, wf, _⟩ := H.WF (VEnvs.WF.empty m s)
  ⟨ves, wf⟩

end Lean4Lean

namespace Lean4Lean.Replay
open Lean hiding Environment Exception
open Kernel

/-- Induction principle for `Replayed`: an invariant of the start environments that is
preserved by every successful checked `addDecl` holds for every replayed environment. -/
theorem Replayed.induction {fuel : FuelConfig} {Start : Environment → Prop}
    (Inv : Environment → Prop) (hstart : ∀ env, Start env → Inv env)
    (hstep : ∀ env d env', Inv env → Lean4Lean.addDecl env d true fuel = .ok env' →
      (d = .quotDecl → env.quotInit = false → hasPreludeEq env = true) → Inv env')
    {env : Environment} (h : Replayed fuel Start env) : Inv env := by
  induction h with
  | start h => exact hstart _ h
  | step _ hadd hq ih => exact hstep _ _ _ ih hadd hq

/-- The dependency-order walk only changes the environment by `addDecl`: a replayed environment
is the result of folding successful checked `addDecl` calls over a list of declarations, from a
start environment. -/
theorem Replayed.foldlM {fuel : FuelConfig} {Start : Environment → Prop} {env : Environment}
    (h : Replayed fuel Start env) :
    ∃ (env₀ : Environment) (ds : List Declaration), Start env₀ ∧
      ds.foldlM (fun env d => Lean4Lean.addDecl env d true fuel) env₀ =
        (.ok env : Except Exception Environment) := by
  induction h with
  | start h => exact ⟨_, [], h, rfl⟩
  | @step env d env' _ hadd _ ih =>
    obtain ⟨env₀, ds, h₀, hds⟩ := ih
    refine ⟨env₀, ds ++ [d], h₀, ?_⟩
    simp only [List.foldlM_append, hds, List.foldlM_cons, List.foldlM_nil]
    simp only [bind, Except.bind, hadd]
    rfl

/-! ### The prelude's `Eq` -/

namespace PreludeEq

theorem strictEq_eq : ∀ {a b : Expr}, strictEq a b = true → a = b
  | .bvar _, .bvar _, h => by simp [strictEq] at h; rw [h]
  | .sort _, .sort _, h => by simp [strictEq] at h; rw [h]
  | .const _ _, .const _ _, h => by simp [strictEq] at h; rw [h.1, h.2]
  | .app _ _, .app _ _, h => by
    simp only [strictEq, Bool.and_eq_true] at h
    rw [strictEq_eq h.1, strictEq_eq h.2]
  | .forallE _ _ _ bi, .forallE _ _ _ bi', h => by
    simp only [strictEq, Bool.and_eq_true, beq_iff_eq] at h
    obtain ⟨⟨⟨hn, ht⟩, hb⟩, hbi⟩ := h
    have : bi = bi' := by cases bi <;> cases bi' <;> first | rfl | cases hbi
    rw [hn, strictEq_eq ht, strictEq_eq hb, this]
  | .bvar _, .sort _, h | .bvar _, .const .., h | .bvar _, .app .., h | .bvar _, .forallE .., h
  | .bvar _, .fvar _, h | .bvar _, .mvar _, h | .bvar _, .lam .., h | .bvar _, .letE .., h
  | .bvar _, .lit _, h | .bvar _, .mdata .., h | .bvar _, .proj .., h => by cases h
  | .sort _, .bvar _, h | .sort _, .const .., h | .sort _, .app .., h | .sort _, .forallE .., h
  | .sort _, .fvar _, h | .sort _, .mvar _, h | .sort _, .lam .., h | .sort _, .letE .., h
  | .sort _, .lit _, h | .sort _, .mdata .., h | .sort _, .proj .., h => by cases h
  | .const .., .bvar _, h | .const .., .sort _, h | .const .., .app .., h
  | .const .., .forallE .., h | .const .., .fvar _, h | .const .., .mvar _, h
  | .const .., .lam .., h | .const .., .letE .., h | .const .., .lit _, h
  | .const .., .mdata .., h | .const .., .proj .., h => by cases h
  | .app .., .bvar _, h | .app .., .sort _, h | .app .., .const .., h
  | .app .., .forallE .., h | .app .., .fvar _, h | .app .., .mvar _, h
  | .app .., .lam .., h | .app .., .letE .., h | .app .., .lit _, h
  | .app .., .mdata .., h | .app .., .proj .., h => by cases h
  | .forallE .., .bvar _, h | .forallE .., .sort _, h | .forallE .., .const .., h
  | .forallE .., .app .., h | .forallE .., .fvar _, h | .forallE .., .mvar _, h
  | .forallE .., .lam .., h | .forallE .., .letE .., h | .forallE .., .lit _, h
  | .forallE .., .mdata .., h | .forallE .., .proj .., h => by cases h
  | .fvar _, _, h | .mvar _, _, h | .lam .., _, h | .letE .., _, h | .lit _, _, h
  | .mdata .., _, h | .proj .., _, h => by cases h

theorem isSafe_spec {ci : ConstantInfo} (h : isSafe ci = true) : ci.safety = .safe := by
  simp only [isSafe, Bool.and_eq_true, Bool.not_eq_true'] at h
  simp [ConstantInfo.safety, h.1, h.2]

theorem eqType_eq (u a b c : Name) : eqType u a b c = VerifyInductive.preludeEqType u a b c :=
  rfl

theorem reflType_eq (u a b : Name) :
    reflType u a b = VerifyInductive.preludeEqReflType u a b := rfl

theorem recType_eq (u v a b c d e f g h : Name) :
    recType u v a b c d e f g h = eqRecTypeExpr u v ⟨a, b, c, d, e, f, g, h⟩ := rfl

theorem isEq_spec {ci : ConstantInfo} (h : isEq ci = true) : IsPreludeEq ci := by
  simp only [isEq, Bool.and_eq_true] at h
  refine ⟨isSafe_spec h.1, ?_⟩
  have h2 := h.2
  split at h2
  · exact ⟨_, _, _, _, ‹ci.levelParams = _›, (strictEq_eq h2).trans (eqType_eq ..)⟩
  · cases h2

theorem isRefl_spec {ci : ConstantInfo} (h : isRefl ci = true) : IsPreludeEqRefl ci := by
  simp only [isRefl, Bool.and_eq_true] at h
  refine ⟨isSafe_spec h.1, ?_⟩
  have h2 := h.2
  split at h2
  · exact ⟨_, _, _, ‹ci.levelParams = _›, (strictEq_eq h2).trans (reflType_eq ..)⟩
  · cases h2

theorem isRec_spec {ci : ConstantInfo} (h : isRec ci = true) : IsPreludeEqRec ci := by
  simp only [isRec, Bool.and_eq_true] at h
  refine ⟨isSafe_spec h.1, ?_⟩
  have h2 := h.2
  split at h2
  · simp only [Bool.and_eq_true, bne_iff_ne, ne_eq] at h2
    exact ⟨_, _, _, h2.1, ‹ci.levelParams = _›, (strictEq_eq h2.2).trans (recType_eq ..)⟩
  · cases h2

end PreludeEq

theorem hasProductionEq_spec {env : Environment} (h : hasPreludeEq env = true) :
    HasPreludeEq env := by
  unfold hasPreludeEq at h
  split at h
  · rename_i e r c he hr hc
    simp only [Bool.and_eq_true] at h
    exact ⟨e, r, c, he, PreludeEq.isEq_spec h.1.1, hr, PreludeEq.isRefl_spec h.1.2, hc,
      PreludeEq.isRec_spec h.2⟩
  · cases h

/-! ### From the driver's walk to `AddDeclChain` -/

/-- Appending a step to an `AddDeclChain`. -/
theorem _root_.Lean4Lean.AddDeclChain.snoc {env env₁ env₂ : Environment} {ds : List Declaration} {d : Declaration}
    (H : AddDeclChain env ds env₁) (hadd : Lean4Lean.addDecl env₁ d (check := true) (fuel := {}) =
      .ok env₂) (hq : d = .quotDecl → HasPreludeEq env₁) : AddDeclChain env (ds ++ [d]) env₂ := by
  induction H with
  | nil => exact .cons hadd hq (.nil _)
  | cons h₁ h₂ _ ih => exact .cons h₁ h₂ (ih hadd hq)

/-- A step that initializes nothing: `quotDecl` on an environment whose quotient module is
initialized returns the environment unchanged. -/
theorem addDecl_quotDecl_of_quotInit {env env' : Environment} (hi : env.quotInit = true)
    (h : Lean4Lean.addDecl env .quotDecl (check := true) (fuel := {}) = .ok env') :
    env' = env := by
  simp only [Lean4Lean.addDecl, Environment.addQuot, hi, if_true] at h
  exact (Except.ok.inj h).symm

/-- Every environment the driver builds with the default fuel is reached by an `AddDeclChain` from its
start environment. -/
theorem Replayed.replay {start env : Environment} (h : Replayed {} (· = start) env) :
    ∃ ds, AddDeclChain start ds env := by
  induction h with
  | start h => exact ⟨[], h ▸ .nil _⟩
  | @step env d env' _ hadd hq ih =>
    obtain ⟨ds, H⟩ := ih
    by_cases hd : d = .quotDecl
    · subst hd
      cases hi : env.quotInit
      · exact ⟨_, H.snoc hadd fun _ => hasProductionEq_spec (hq rfl hi)⟩
      · exact ⟨ds, addDecl_quotDecl_of_quotInit hi hadd ▸ H⟩
    · exact ⟨_, H.snoc hadd fun h => absurd h hd⟩

/-- A replay result from the empty environment with the default fuel is modelled by well-formed
abstract environments. -/
theorem ReplayResult.wf_empty {cfg : Config} (hfuel : cfg.fuel = {}) {m : Name} {s : Bool}
    {decl : Option Name} (r : ReplayResult cfg (Kernel.Environment.empty m s) decl) :
    ∃ ves' : VEnvs, ves'.WF r.env := by
  have hr := r.replayed
  rw [hfuel] at hr
  obtain ⟨ds, H⟩ := hr.replay
  exact H.WF_empty

/-- A replay result from a well-formed start environment with canonical `Eq` is modelled by
well-formed abstract environments with canonical `Eq` that extend the start's. -/
theorem ReplayResult.wf_of_WF {cfg : Config} (hfuel : cfg.fuel = {}) {start : Environment}
    {decl : Option Name} (r : ReplayResult cfg start decl) {ves : VEnvs} (wf : ves.WF start)
    (heq : ves.HasCanonicalEq) :
    ∃ ves' : VEnvs, ves'.WF r.env ∧ ves'.HasCanonicalEq ∧
      ∀ safety, ves.venv safety ≤ ves'.venv safety := by
  have hr := r.replayed
  rw [hfuel] at hr
  refine Replayed.induction (fun env => ∃ ves' : VEnvs, ves'.WF env ∧ ves'.HasCanonicalEq ∧
      ∀ safety, ves.venv safety ≤ ves'.venv safety) ?_ ?_ hr
  · rintro _ rfl
    exact ⟨ves, wf, heq, fun _ => VEnv.LE.rfl⟩
  · rintro env d env' ⟨ves₁, wf₁, heq₁, hle₁⟩ hadd _
    obtain ⟨ves₂, wf₂, heq₂, hle₂⟩ := addDecl.WFHasCanonicalEq wf₁ heq₁ d env' hadd
    exact ⟨ves₂, wf₂, heq₂, fun safety => (hle₁ safety).trans (hle₂ safety)⟩

/-- **Soundness of fresh replay.** If the pure replay of a source constant table `src` from the
empty environment (`--fresh` mode, default fuel, all constants) succeeds, the environment it
built is modelled by well-formed abstract environments, and every safe, non-partial source
constant is present in it and agrees with the source constant (up to `==`, see the module
docstring). There is no hypothesis: the base case is `VEnvs.WF.empty`, and the driver only
initializes the quotient module once the prelude's `Eq` is present (`hasPreludeEq`), which is
what the abstract model of `quotDecl` needs (`AddDeclChain.WF`). -/
theorem replayFresh.WF {src : Std.HashMap Name ConstantInfo} {mainModule : Name} :
    (replayFresh src mainModule).WF fun r =>
      (∃ ves' : VEnvs, ves'.WF r.env) ∧
      ∀ n ci, src[n]? = some ci → ci.isUnsafe = false → ci.isPartial = false →
        ∃ ci', r.env.find? n = some ci' ∧ (ci' == ci) = true := by
  intro r _
  exact ⟨r.wf_empty rfl, fun n ci hci hu hp => r.agree n (r.complete rfl n ci hci hu hp) ci hci⟩

/-- **Soundness of replay on top of imports.** If the pure replay of a module's constant table
`src` into the environment `env` of its imports (default fuel, all constants) succeeds, and `env`
is modelled by well-formed abstract environments with canonical `Eq`, then so is the environment
the replay built (extending the model of `env`), and every safe, non-partial source constant is
present in it and agrees with the source constant. The imports are trusted in this mode
(`lake exe lean4lean M` without `--fresh`): the well-formedness of `env` is a hypothesis, not
checked by the replay. -/
theorem replayFromImports.WF {src : Std.HashMap Name ConstantInfo} {checkQuot : Bool}
    {env : Environment} {ves : VEnvs} (wf : ves.WF env) (heq : ves.HasCanonicalEq) :
    (replayPure { newConstants := src, checkQuot } env).WF fun r =>
      (∃ ves' : VEnvs, ves'.WF r.env ∧ ves'.HasCanonicalEq ∧
        ∀ safety, ves.venv safety ≤ ves'.venv safety) ∧
      ∀ n ci, src[n]? = some ci → ci.isUnsafe = false → ci.isPartial = false →
        ∃ ci', r.env.find? n = some ci' ∧ (ci' == ci) = true := by
  intro r _
  exact ⟨r.wf_of_WF rfl wf heq,
    fun n ci hci hu hp => r.agree n (r.complete rfl n ci hci hu hp) ci hci⟩

end Lean4Lean.Replay
