import Lean4Lean.Replay
import Lean4Lean.Verify.Environment

/-!
# Soundness of the replay driver

`Lean4Lean.Replay.replayCore` (in `Lean4Lean/Replay.lean`) is the driver behind
`lake exe lean4lean`: it walks the constants of a source environment in dependency order,
rebuilds a `Declaration` from each `ConstantInfo`, and adds it with the verified kernel
`Lean4Lean.addDecl`; it then compares the constructors and recursors generated by the kernel with
the source's, and finally checks that every replayed constant is present in the environment it
built and agrees with the source constant.

The core carries its own soundness evidence in its types: its state records that the current
environment is reached from the start environment by successful `addDecl` calls (`Replayed`),
and its result (`ReplayResult`) records the final agreement check. So the theorems below are about
*every* `ReplayResult`, and apply to the pure instance `replayPure`/`replayFresh` as well as to the
IO instance the executable runs (`replay`, `replayFromFresh`, `replayFromImports`), without
unfolding the dependency walk (a `partial def`).

Agreement is up to `==` on `ConstantInfo`: the derived equality, which compares expressions with
`Expr.eqv`, so it ignores binder names and binder annotations. This is the same comparison the
driver has always used for constructors and recursors.

The per-declaration theorems are stated for the default fuel `{}`, which is also the executable's
configuration when no `--config` flag is given. The walk lemma `Replayed.foldlM` holds for any
fuel.
-/

namespace Lean4Lean.Replay
open Lean hiding Environment Exception
open Kernel

/-- Induction principle for `Replayed`: an invariant of the start environments that is
preserved by every successful checked `addDecl` holds for every replayed environment. -/
theorem Replayed.induction {fuel : FuelConfig} {Start : Environment → Prop}
    (Inv : Environment → Prop) (hstart : ∀ env, Start env → Inv env)
    (hstep : ∀ env d env', Inv env → Lean4Lean.addDecl env d true fuel = .ok env' → Inv env')
    {env : Environment} (h : Replayed fuel Start env) : Inv env := by
  induction h with
  | start h => exact hstart _ h
  | step _ hadd ih => exact hstep _ _ _ ih hadd

/-- The dependency-order walk only changes the environment by `addDecl`: a replayed environment
is the result of folding successful checked `addDecl` calls over a list of declarations, from a
start environment. -/
theorem Replayed.foldlM {fuel : FuelConfig} {Start : Environment → Prop} {env : Environment}
    (h : Replayed fuel Start env) :
    ∃ (env₀ : Environment) (ds : List Declaration), Start env₀ ∧
      ds.foldlM (fun env d => Lean4Lean.addDecl env d true fuel) env₀ =
        (.ok env : Except Exception Environment) := by
  induction h with
  | start h => exact ⟨_, [], h, rfl⟩
  | @step env d env' _ hadd ih =>
    obtain ⟨env₀, ds, h₀, hds⟩ := ih
    refine ⟨env₀, ds ++ [d], h₀, ?_⟩
    simp only [List.foldlM_append, hds, List.foldlM_cons, List.foldlM_nil]
    simp only [bind, Except.bind, hadd]
    rfl

/-- The list form of replay soundness from `env₀`: folding successful checked `addDecl` calls
(with the default fuel) over any list of declarations yields an environment modelled by
well-formed abstract environments. For the empty environment this is the list-form replay theorem
(`VEnvs.WF.empty` together with the `Eq` bootstrap of `Verify/CanonicalEqRealization.lean`); for a
well-formed environment with canonical `Eq` it is `ListReplaySound.of_WF`. -/
def ListReplaySound (env₀ : Environment) : Prop :=
  ∀ ds : List Declaration,
    (ds.foldlM (fun env d => Lean4Lean.addDecl env d (check := true) (fuel := {})) env₀).WF
      fun env' => ∃ ves' : VEnvs, ves'.WF env'

/-- A replay result from a start environment in which list replay is sound is modelled by
well-formed abstract environments. -/
theorem ReplayResult.wf {cfg : Config} (hfuel : cfg.fuel = {}) {start : Environment}
    {decl : Option Name} (r : ReplayResult cfg start decl) (hstart : ListReplaySound start) :
    ∃ ves' : VEnvs, ves'.WF r.env := by
  have hr := r.replayed
  rw [hfuel] at hr
  obtain ⟨env₀, ds, rfl, hds⟩ := hr.foldlM
  exact hstart ds _ hds

/-- A replay result from a well-formed start environment with canonical `Eq` is modelled by
well-formed abstract environments with canonical `Eq` that extend the start's. -/
theorem ReplayResult.wf_of_WF {cfg : Config} (hfuel : cfg.fuel = {}) {start : Environment}
    {decl : Option Name} (r : ReplayResult cfg start decl) {ves : VEnvs} (wf : ves.WF start)
    (heq : ves.HasCanonicalEq) :
    ∃ ves' : VEnvs, ves'.WF r.env ∧ ves'.HasCanonicalEq ∧
      ∀ safety, ves.venv safety ≤ ves'.venv safety := by
  have hr := r.replayed
  rw [hfuel] at hr
  refine Replayed.induction (fun env => ∃ ves' : VEnvs, ves'.WF env ∧ ves'.HasCanonicalEq ∧
      ∀ safety, ves.venv safety ≤ ves'.venv safety) ?_ ?_ hr
  · rintro _ rfl
    exact ⟨ves, wf, heq, fun _ => VEnv.LE.rfl⟩
  · rintro env d env' ⟨ves₁, wf₁, heq₁, hle₁⟩ hadd
    obtain ⟨ves₂, wf₂, heq₂, hle₂⟩ := addDecl.WFHasCanonicalEq wf₁ heq₁ d trivial env' hadd
    exact ⟨ves₂, wf₂, heq₂, fun safety => (hle₁ safety).trans (hle₂ safety)⟩

/-- List replay is sound from a well-formed environment with canonical `Eq`. -/
theorem ListReplaySound.of_WF {env₀ : Environment} {ves : VEnvs} (wf : ves.WF env₀)
    (heq : ves.HasCanonicalEq) : ListReplaySound env₀ := by
  intro ds
  induction ds generalizing env₀ ves with
  | nil => rintro _ ⟨⟩; exact ⟨ves, wf⟩
  | cons d ds ih =>
    intro env' h
    simp only [List.foldlM_cons, bind, Except.bind] at h
    split at h
    · cases h
    · rename_i env₁ hadd
      obtain ⟨ves₁, wf₁, heq₁, _⟩ := addDecl.WFHasCanonicalEq wf heq d trivial env₁ hadd
      exact ih wf₁ heq₁ env' h

/-- **Soundness of fresh replay.** If the pure replay of a source constant table `src` from the
empty environment (`--fresh` mode, default fuel, all constants) succeeds, the environment it
built is modelled by well-formed abstract environments, and every safe, non-partial source
constant is present in it and agrees with the source constant (up to `==`, see the module
docstring). The hypothesis `hfresh` is the list-form replay theorem from the empty environment. -/
theorem replayFresh.WF {src : Std.HashMap Name ConstantInfo} {mainModule : Name}
    (hfresh : ListReplaySound (freshStart mainModule)) :
    (replayFresh src mainModule).WF fun r =>
      (∃ ves' : VEnvs, ves'.WF r.env) ∧
      ∀ n ci, src[n]? = some ci → ci.isUnsafe = false → ci.isPartial = false →
        ∃ ci', r.env.find? n = some ci' ∧ (ci' == ci) = true := by
  intro r _
  exact ⟨r.wf rfl hfresh, fun n ci hci hu hp => r.agree n (r.complete rfl n ci hci hu hp) ci hci⟩

/-- **Soundness of replay on top of imports.** If the pure replay of a module's constant table
`src` into the environment `env` of its imports (default fuel, all constants) succeeds, and `env`
is modelled by well-formed abstract environments with canonical `Eq`, then so is the environment
the replay built (extending the model of `env`), and every safe, non-partial source constant is
present in it and agrees with the source constant. The imports are trusted in this mode
(`lake exe lean4lean M` without `--fresh`): the well-formedness of `env` is a hypothesis, not
checked by the replay. -/
theorem replayFromImports.WF {src : Std.HashMap Name ConstantInfo} {checkQuot : Bool}
    {env : Environment} {ves : VEnvs} (wf : ves.WF env) (heq : ves.HasCanonicalEq) :
    (replayPure { newConstants := src, checkQuot } env).WF fun r =>
      (∃ ves' : VEnvs, ves'.WF r.env ∧ ves'.HasCanonicalEq ∧
        ∀ safety, ves.venv safety ≤ ves'.venv safety) ∧
      ∀ n ci, src[n]? = some ci → ci.isUnsafe = false → ci.isPartial = false →
        ∃ ci', r.env.find? n = some ci' ∧ (ci' == ci) = true := by
  intro r _
  exact ⟨r.wf_of_WF rfl wf heq,
    fun n ci hci hu hp => r.agree n (r.complete rfl n ci hci hu hp) ci hci⟩

end Lean4Lean.Replay
