import Lean4Lean.Theory.Typing.AnchoredOriginalRawParameterTypeRoute
import Lean4Lean.Theory.Typing.AnchoredOriginalAmbientTypeRouteGeneration
import Lean4Lean.Theory.Typing.AnchoredOriginalAmbientParameterComparison

/-! The seven original parameter-cell edges retain positive generation of
all four actual prefix frames. This does not construct those prefixes. -/
namespace Lean4Lean.AnchoredSource.Adapted.OriginalRecordSource
open VExpr VEnv AnchoredProfiles AnchoredSemantics OriginalClosureMeasure
open OriginalEndpointFactor OriginalTail
set_option backward.isDefEq.respectTransparency false
set_option Elab.async false

section
variable
    {env familyEnv baseEnv typesEnv ctorEnv : VEnv} {U : Nat}
    {registry : CanonicalHead.Registry} {target common : List VExpr}
    {base : OriginalCaptureBase env U registry target} {commonCaps : CaptureCaps}
    {familyContext : ContextDerivation familyEnv U familySource}
    {seedContext universeContext : ContextDerivation baseEnv U seedSource}
    {requestedContext : ContextDerivation typesEnv U requestedSource}
    {ctorContext : ContextDerivation ctorEnv U ctorSource}
    (familyGraph : OriginalCaptureMap (common := common) familyContext raw)
    (seedGraph : OriginalCaptureMap (common := common) seedContext raw)
    (universeGraph : OriginalCaptureMap (common := common) universeContext raw)
    (requestedGraph : OriginalCaptureMap (common := common) requestedContext raw)
    (ctorGraph : OriginalCaptureMap (common := common) ctorContext raw)
    (family : EndpointRef familyEnv U familySource familyDomain (.sort familyLevel))
    (familyProvenance : EndpointProvenance familyContext (.ref family))
    (familyCell : Derivation baseEnv U seedSource seedDomain familyDomain (.sort familySort))
    (universeCell : Derivation baseEnv U seedSource seedDomain requestedDomain (.sort universeSort))
    (ctorCell : Derivation typesEnv U requestedSource requestedDomain ctorDomain (.sort ctorSort))
    (constructor : EndpointRef ctorEnv U ctorSource ctorDomain (.sort ctorLevel))
    (ctorProvenance : EndpointProvenance ctorContext (.ref constructor))
    (familyOrdered : familyEnv.Ordered) (baseOrdered : baseEnv.Ordered)
    (typesOrdered : typesEnv.Ordered) (ctorOrdered : ctorEnv.Ordered)
    (baseBelow : baseEnv ≤ env) (typesBelow : typesEnv ≤ env)
    (familyBelow : familyEnv ≤ env)
    (initial : List Closure)
    (seedFrame : AmbientParameterReplyFrame base commonCaps seedGraph commonLeft commonRight)
    (universeFrame : AmbientParameterReplyFrame base commonCaps universeGraph commonLeft commonRight)
    (requestedFrame : AmbientParameterReplyFrame base commonCaps requestedGraph commonLeft commonRight)
    (ctorFrame : AmbientParameterReplyFrame base commonCaps ctorGraph commonLeft commonRight)

include familyBelow in
/-- The low-level retained history really is generated by the supplied
actual prefixes. There is no universal alignment hypothesis. -/
theorem rawParameterCellsTypeRoute_ambientGenerated :
    (rawParameterCellsTypeRoute familyGraph seedGraph universeGraph requestedGraph ctorGraph
      family familyProvenance familyCell universeCell ctorCell constructor ctorProvenance
      familyOrdered baseOrdered typesOrdered ctorOrdered baseBelow typesBelow initial
      seedFrame.toParameterReplyFrame universeFrame.toParameterReplyFrame
      requestedFrame.toParameterReplyFrame ctorFrame.toParameterReplyFrame).AmbientGenerated base commonCaps := by
  refine ⟨?_, ?_, ?_⟩
  · simp [rawParameterCellsTypeRoute, RawGeneratedTypeRoute.WellFormed.eq_def]
  · simp only [rawParameterCellsTypeRoute, RawGeneratedTypeRoute.Ambient.eq_def]
    exact ⟨⟨familyBelow, seedFrame.generation.ambient.2.below⟩,
      trivial, ⟨seedFrame.generation.ambient.2.below, universeFrame.generation.ambient.2.below⟩,
      trivial, ⟨universeFrame.generation.ambient.2.below, requestedFrame.generation.ambient.2.below⟩,
      trivial, ⟨requestedFrame.generation.ambient.2.below, ctorFrame.generation.ambient.2.below⟩⟩
  · intro boxed member
    simp only [rawParameterCellsTypeRoute, RawGeneratedTypeRoute.frames.eq_def,
      List.mem_append, List.mem_cons, List.not_mem_nil, or_false, false_or] at member
    rcases member with rfl | rfl | rfl | rfl
    · exact seedFrame.generation
    · exact universeFrame.generation
    · exact requestedFrame.generation
    · exact ctorFrame.generation

end
end Lean4Lean.AnchoredSource.Adapted.OriginalRecordSource
