import Lean4Lean.Theory.Typing.NativeConstructorRigidity
import Lean4Lean.Theory.Typing.QuotPrefixReduction
import Batteries.Tactic.OpenPrivate

/-! A structure's projection metadata names the only constructor at which
native computation can produce a value of that structure.

Every installed equation whose major is a constructor application is either
generated by the very declaration that installed the constructor's result
family, or copied from an earlier such equation. Projection metadata is only
ever registered for fresh family names. Hence, if a native equation's major
constructor returns a registered structure, that constructor is the
structure's projection constructor. The proof follows the actual `WF'`
history; no confluence, injectivity or uniqueness of typing is used. -/

namespace Lean4Lean.VEnv
open InductiveSignature VExpr
open private addDefEqs_as_rules addConsts_as_values defeqs_addRules
  from Lean4Lean.Theory.Typing.NativeConstructorRigidity
set_option linter.unusedSectionVars false

variable {env env' : VEnv}

theorem hasConstructorMajor_unique {df : VDefEq} (h : df.HasConstructorMajor a)
    (h' : df.HasConstructorMajor b) : a = b := by
  obtain ⟨fl, ll, al, hl⟩ := h
  obtain ⟨fr, lr, ar, hr⟩ := h'
  have he := (VExpr.app.inj (hl.symm.trans hr)).2
  have hh := congrArg (fun e : VExpr => e.getAppFnArgs.1) he
  simp only [VExpr.getAppFnArgs_mkApps_head] at hh
  exact (VExpr.const.inj hh).1

/-- The declared result family of a constant: the head of its type after the
whole `forallE` telescope. -/
def ResultFamily (env : VEnv) (c F : Name) : Prop :=
  ∃ ci ls, env.constants c = some ci ∧ ci.type.forallResult.getAppFnArgs.1 = .const F ls

theorem ResultFamily.of_le (hle : env ≤ env') (hc : env.constants c = some ci)
    (H : env'.ResultFamily c F) : env.ResultFamily c F := by
  obtain ⟨ci', ls, h', hh⟩ := H
  rw [hle.constants hc] at h'
  cases h'
  exact ⟨ci, ls, hc, hh⟩

theorem ResultFamily.mono (hle : env ≤ env') (H : env.ResultFamily c F) :
    env'.ResultFamily c F := by
  obtain ⟨ci, ls, h, hh⟩ := H
  exact ⟨ci, ls, hle.constants h, hh⟩

/-- The argument of an application below the leading lambdas of a typed term
is itself typed. -/
theorem HasType.stripLams_app_arg (henv : env.Ordered) {Γ : List VExpr}
    (hΓ : OnCtx Γ (env.IsType U)) {e T : VExpr} (H : env.HasType U Γ e T)
    (hs : e.stripLams = .app fn a) :
    ∃ Γ' T', OnCtx Γ' (env.IsType U) ∧ env.HasType U Γ' a T' := by
  induction e generalizing Γ T with
  | lam domain body _ ih =>
    rcases H.lam_inv henv hΓ with ⟨hdomain, _, hbody⟩
    exact ih (Γ := domain :: Γ) ⟨hΓ, hdomain⟩ hbody hs
  | app f x =>
    change VExpr.app f x = _ at hs
    cases hs
    rcases H.app_inv henv hΓ with ⟨_, _, _, hx⟩
    exact ⟨_, _, hΓ, hx⟩
  | _ => cases hs

/-- The major constructor of an installed equation is a declared constant. -/
theorem Ordered.constructorMajor_declared (henv : env.Ordered) (hdf : env.defeqs eq)
    (hm : eq.HasConstructorMajor c) : ∃ ci, env.constants c = some ci := by
  obtain ⟨fn, levels, args, hs⟩ := hm
  obtain ⟨Γ', _, hΓ', ha⟩ := HasType.stripLams_app_arg henv (Γ := []) ⟨⟩ (henv.defEqWF hdf).1 hs
  have hh : (VExpr.mkApps (.const c levels) args).getAppFnArgs.1 = .const c levels :=
    VExpr.getAppFnArgs_mkApps_head _ _
  exact ha.head_const_lookup henv hΓ' (by rw [VExpr.stripLams_of_head_const hh]; exact hh)

/-- The result head of a well-formed type is a declared constant. -/
theorem IsType.forallResult_head_declared (henv : env.Ordered) {Γ : List VExpr}
    (hΓ : OnCtx Γ (env.IsType U)) {type : VExpr} (H : env.IsType U Γ type)
    (hh : type.forallResult.getAppFnArgs.1 = .const F ls) :
    ∃ cF, env.constants F = some cF := by
  induction type generalizing Γ with
  | forallE domain body _ ih =>
    obtain ⟨_, h⟩ := H
    obtain ⟨⟨_, hd⟩, _, hb⟩ := h.forallE_inv henv
    exact ih (Γ := domain :: Γ) ⟨hΓ, _, hd⟩ ⟨_, hb⟩ hh
  | lam => cases hh
  | _ =>
    obtain ⟨_, h⟩ := H
    exact h.head_const_lookup henv hΓ hh

theorem Ordered.resultFamily_declared (henv : env.Ordered) (H : env.ResultFamily c F) :
    ∃ cF, env.constants F = some cF := by
  obtain ⟨ci, ls, hc, hh⟩ := H
  exact IsType.forallResult_head_declared henv (Γ := []) ⟨⟩ (henv.constWF hc) hh

/-- Projection metadata names the only constructor at which an installed
equation can compute a value of the structure. -/
def StructureCtorCoherent (env : VEnv) : Prop :=
  ∀ F info, env.projections F info → ∀ eq c, env.defeqs eq → eq.HasConstructorMajor c →
    env.ResultFamily c F → c = info.ctorName

private theorem StructureCtorCoherent.extend (H : StructureCtorCoherent env)
    (henv : env.Ordered) (hle : env ≤ env')
    (hproj : ∀ F info, env'.projections F info → env.projections F info ∨ env.constants F = none)
    (hnew : ∀ eq, env'.defeqs eq → ¬env.defeqs eq → ∀ c, eq.HasConstructorMajor c → ∀ F,
      env'.ResultFamily c F → ∀ info, env'.projections F info → c = info.ctorName) :
    StructureCtorCoherent env' := by
  classical
  intro F info hp eq c hd hm hr
  by_cases hold : env.defeqs eq
  · obtain ⟨ci, hci⟩ := henv.constructorMajor_declared hold hm
    have hr' := hr.of_le hle hci
    obtain ⟨cF, hcF⟩ := henv.resultFamily_declared hr'
    rcases hproj F info hp with hp' | hfresh
    · exact H F info hp' eq c hold hm hr'
    · rw [hcF] at hfresh; cases hfresh
  · exact hnew eq hd hold c hm F hr info hp

private theorem no_new_defeqs (h : env'.defeqs = env.defeqs) :
    ∀ eq, env'.defeqs eq → ¬env.defeqs eq → ∀ c, eq.HasConstructorMajor c → ∀ F,
      env'.ResultFamily c F → ∀ info, env'.projections F info → c = info.ctorName := by
  intro eq hd hold
  rw [h] at hd
  exact absurd hd hold

private theorem old_projections (h : env'.projections = env.projections) :
    ∀ F info, env'.projections F info → env.projections F info ∨ env.constants F = none := by
  intro F info hp
  rw [h] at hp
  exact .inl hp

private theorem definition_no_major (hm : (VDefVal.toDefEq value).HasConstructorMajor c) : False := by
  obtain ⟨fn, levels, args, hs⟩ := hm
  cases hs

private theorem StructureCtorCoherent.addInduct (H : StructureCtorCoherent env)
    (henv : env.Ordered) (hadd : env.AddInduct decl env') : StructureCtorCoherent env' := by
  cases hadd with
  | @intro block installed hdecl hcompile hblock hinstall =>
    simp only [VInductBlock.install, Option.bind_eq_bind, Option.bind_eq_some_iff,
      Option.pure_def, Option.some.injEq] at hinstall
    obtain ⟨envTypes, htypes, envCtors, hctors, envRecs, hrecs, rfl⟩ := hinstall
    have hle : env ≤ (envRecs.addDefEqRules block.rules) :=
      (((VEnv.addConstVals_le htypes).trans (VEnv.addConstVals_le hctors)).trans
        (VEnv.addProjections_le.trans (VEnv.addConstVals_le hrecs))).trans VEnv.addDefEqRules_le
    have hdf : envRecs.defeqs = env.defeqs :=
      (VEnv.addConstVals_defeqs hrecs).trans <| (VEnv.addProjections_defeqs _ _).trans <|
        (VEnv.addConstVals_defeqs hctors).trans (VEnv.addConstVals_defeqs htypes)
    have hproj : ∀ F info, (envRecs.addDefEqRules block.rules).projections F info →
        (∃ entry ∈ block.projections, F = entry.typeName ∧ info = entry.info) ∨
          env.projections F info := by
      intro F info hp
      rw [VEnv.addDefEqRules_projections, VEnv.addConstVals_projections hrecs,
        VEnv.addProjections_iff, VEnv.addConstVals_projections hctors,
        VEnv.addConstVals_projections htypes] at hp
      exact hp
    have hfreshEntry : ∀ entry ∈ block.projections, env.constants entry.typeName = none ∧
        ∃ type ∈ decl.types, ∃ ctor, type.ctors = [ctor] ∧ entry.typeName = type.name ∧
          entry.info.ctorName = ctor.name := by
      intro entry hentry
      rw [hcompile.projections] at hentry
      obtain ⟨type, htype, ctor, hct, rfl⟩ := decl.projectionEntries_origin hentry
      refine ⟨VEnv.addConstVals_names_fresh htypes type.toVConstVal ?_,
        type, htype, ctor, hct, rfl, rfl⟩
      rw [hcompile.types]
      exact List.mem_map.mpr ⟨type, htype, rfl⟩
    apply H.extend henv hle
    · intro F info hp
      rcases hproj F info hp with ⟨entry, hentry, rfl, rfl⟩ | hp
      · exact .inr (hfreshEntry entry hentry).1
      · exact .inl hp
    · intro eq hd hold c hm F hr info hp
      have hd' : eq ∈ block.rules := by
        rcases defeqs_addRules.mp hd with hm | ho
        · exact hm
        · rw [hdf] at ho; exact absurd ho hold
      obtain ⟨name, horigin, hctor | ⟨prior, hprior, hpm⟩⟩ :=
        hcompile.compiled.equation_major_origin eq hd'
      · have hn := hasConstructorMajor_unique hm horigin
        obtain ⟨ctor, hctorMem, hname⟩ := hctor
        have hc : c = ctor.name := hn.trans hname
        subst hc
        obtain ⟨type, htype, hct⟩ := List.mem_flatMap.mp hctorMem
        obtain ⟨ls, hres⟩ := hcompile.compiled.ctor_result type htype ctor hct
        have hcLookup : (envRecs.addDefEqRules block.rules).constants ctor.name =
            some ctor.toVConstant := by
          have hc : ctor ∈ block.ctors := by rw [hcompile.ctors]; exact hctorMem
          have := VEnv.addConstVals_get hctors hc
          exact ((VEnv.addProjections_le.trans (VEnv.addConstVals_le hrecs)).trans
            VEnv.addDefEqRules_le).constants this
        obtain ⟨ci, ls', hci, hh⟩ := hr
        rw [hcLookup] at hci
        cases hci
        have hF : F = type.name := (VExpr.const.inj (hh.symm.trans hres)).1
        subst hF
        rcases hproj type.name info hp with ⟨entry, hentry, hn, rfl⟩ | hold'
        · obtain ⟨_, type', htype', ctor', hct', hn', hcn⟩ := hfreshEntry entry hentry
          have htt : type = type' :=
            VInductDecl.type_eq_of_mem_name hcompile.sourceNames htype htype' (hn.trans hn')
          subst htt
          rw [hct'] at hct
          rw [List.mem_singleton.mp hct, hcn]
        · obtain ⟨_, hc⟩ := henv.projectionConstant hold'
          have hfresh := VEnv.addConstVals_names_fresh htypes type.toVConstVal (by
            rw [hcompile.types]; exact List.mem_map.mpr ⟨type, htype, rfl⟩)
          rw [hfresh] at hc
          cases hc
      · have hn := hasConstructorMajor_unique hm horigin
        subst hn
        obtain ⟨ci, hci⟩ := henv.constructorMajor_declared hprior hpm
        have hr' := hr.of_le hle hci
        obtain ⟨cF, hcF⟩ := henv.resultFamily_declared hr'
        rcases hproj F info hp with ⟨entry, hentry, rfl, rfl⟩ | hp'
        · rw [(hfreshEntry entry hentry).1] at hcF; cases hcF
        · exact H F info hp' prior c hprior hpm hr'

private theorem StructureCtorCoherent.addQuot (H : StructureCtorCoherent env)
    (henv : env.Ordered) (hadd : env.addQuot = some env') : StructureCtorCoherent env' := by
  simp only [VEnv.addQuot, Option.bind_eq_bind, Option.bind_eq_some_iff,
    Option.pure_def, Option.some.injEq] at hadd
  obtain ⟨a, ha, b, hb, c, hc, d, hd, rfl⟩ := hadd
  have hle : env ≤ d.addDefEq quotDefEq :=
    ((((VEnv.addConst_le ha).trans (VEnv.addConst_le hb)).trans
      (VEnv.addConst_le hc)).trans (VEnv.addConst_le hd)).trans VEnv.addDefEq_le
  have hprojEq : (d.addDefEq quotDefEq).projections = env.projections :=
    (VEnv.addConst_projections hd).trans <| (VEnv.addConst_projections hc).trans <|
      (VEnv.addConst_projections hb).trans (VEnv.addConst_projections ha)
  have hdfEq : d.defeqs = env.defeqs :=
    (VEnv.addConst_defeqs hd).trans <| (VEnv.addConst_defeqs hc).trans <|
      (VEnv.addConst_defeqs hb).trans (VEnv.addConst_defeqs ha)
  apply H.extend henv hle (old_projections hprojEq)
  intro eq hdq hold name hm F hr info hp
  have heq : eq = quotDefEq := by
    rcases hdq with h | h
    · exact h
    · rw [hdfEq] at h; exact absurd h hold
  subst heq
  rw [hprojEq] at hp
  obtain ⟨_, hcF⟩ := henv.projectionConstant hp
  have hmk : quotDefEq.HasConstructorMajor ``Quot.mk :=
    ⟨_, [.param 0], [.bvar 5, .bvar 4, .bvar 0], rfl⟩
  have hn := hasConstructorMajor_unique hm hmk
  subst hn
  obtain ⟨ci, ls, hci, hh⟩ := hr
  have hmkLookup : (d.addDefEq quotDefEq).constants ``Quot.mk = some quotMkConst :=
    ((VEnv.addConst_le hc).trans ((VEnv.addConst_le hd).trans VEnv.addDefEq_le)).constants
      (VEnv.addConst_self hb)
  rw [hmkLookup] at hci
  cases hci
  have hq : quotMkConst.type.forallResult.getAppFnArgs.1 = .const ``Quot [.param 0] := by rfl
  have hF : F = ``Quot := (VExpr.const.inj (hh.symm.trans hq)).1
  subst hF
  unfold VEnv.addConst at ha
  split at ha
  · cases ha
  · rename_i hnone
    rw [hnone] at hcF
    cases hcF

/-- Every well-formed declaration history keeps projection constructors
coherent with native constructor computation. -/
theorem WF'.structureCtorCoherent (H : VEnv.WF' ds env) : StructureCtorCoherent env := by
  induction H with
  | empty => intro _ _ h; cases h
  | @decl d env' ds env hdecl hbase ih =>
    have henv := (show env.WF from ⟨ds, hbase⟩).ordered
    cases hdecl with
    | «axiom» _ hadd | «opaque» _ hadd =>
      exact ih.extend henv (VEnv.addConst_le hadd)
        (old_projections (VEnv.addConst_projections hadd))
        (no_new_defeqs (VEnv.addConst_defeqs hadd))
    | «example» => exact ih
    | @«def» _ _ ci _ hadd =>
      apply ih.extend henv ((VEnv.addConst_le hadd).trans VEnv.addDefEq_le)
        (old_projections (by
          have h := VEnv.addConst_projections hadd
          exact h))
      intro eq hd hold c hm
      rcases hd with rfl | hd
      · exact (definition_no_major hm).elim
      · rw [VEnv.addConst_defeqs hadd] at hd; exact absurd hd hold
    | mutualDef _ hadd _ =>
      have hadd' := addConsts_as_values ▸ hadd
      apply ih.extend henv
      · rw [addDefEqs_as_rules]
        exact (VEnv.addConsts_le hadd).trans VEnv.addDefEqRules_le
      · apply old_projections
        rw [addDefEqs_as_rules, VEnv.addDefEqRules_projections, VEnv.addConstVals_projections hadd']
      · intro eq hd hold c hm
        rw [addDefEqs_as_rules] at hd
        rcases defeqs_addRules.mp hd with hmem | hd
        · obtain ⟨value, _, rfl⟩ := List.mem_map.mp hmem
          exact (definition_no_major hm).elim
        · rw [VEnv.addConstVals_defeqs hadd'] at hd; exact absurd hd hold
    | quot _ hadd => exact ih.addQuot henv hadd
    | induct _ hadd => exact ih.addInduct henv hadd
  | inductEliminators _ _ _ _ _ _ _ _ ih =>
    intro F info hp eq c hd hm hr
    exact ih F info hp eq c hd hm ⟨hr.choose, hr.choose_spec.choose, hr.choose_spec.choose_spec⟩
  | @inductProjections baseDecls ds base envTypes envCtors decl block
      hbase _ hsource _ _ _ _ _ htypesSource _ hprojections htypes hctors ihBase ihCtors =>
    have hbaseOrdered := (show base.WF from ⟨baseDecls, hbase⟩).ordered
    have hle : base ≤ envCtors.addProjections block.projections :=
      (VEnv.addConstVals_le htypes).trans ((VEnv.addConstVals_le hctors).trans VEnv.addProjections_le)
    have hdf : (envCtors.addProjections block.projections).defeqs = base.defeqs :=
      (VEnv.addProjections_defeqs _ _).trans <|
        (VEnv.addConstVals_defeqs hctors).trans (VEnv.addConstVals_defeqs htypes)
    intro F info hp eq c hd hm hr
    rw [VEnv.addProjections_iff] at hp
    rcases hp with ⟨entry, hentry, rfl, rfl⟩ | hp
    · rw [hdf] at hd
      obtain ⟨ci, hci⟩ := hbaseOrdered.constructorMajor_declared hd hm
      obtain ⟨cF, hcF⟩ := hbaseOrdered.resultFamily_declared (hr.of_le hle hci)
      rw [hprojections] at hentry
      obtain ⟨type, htype, ctor, _, rfl⟩ := decl.projectionEntries_origin hentry
      have hfresh := VEnv.addConstVals_names_fresh htypes type.toVConstVal (by
        rw [htypesSource]; exact List.mem_map.mpr ⟨type, htype, rfl⟩)
      rw [hfresh] at hcF
      cases hcF
    · rw [VEnv.addProjections_defeqs] at hd
      obtain ⟨ci, ls, hci, hh⟩ := hr
      rw [VEnv.addProjections_constants] at hci
      exact ihCtors F info hp eq c hd hm ⟨ci, ls, hci, hh⟩

theorem WF.structureCtorCoherent (H : env.WF) : StructureCtorCoherent env :=
  H.choose_spec.structureCtorCoherent

end Lean4Lean.VEnv
