import Lean4Lean.Theory.Typing.EnvLemmas
import Lean4Lean.Theory.Typing.Strong
import Lean4Lean.Theory.Typing.Injectivity
import Lean4Lean.Theory.Typing.ProjectionLemmas
import Lean4Lean.Theory.Typing.RecursorLemmas
import Lean4Lean.Theory.Typing.ChurchRosser
import Lean4Lean.Theory.Typing.InductiveParams
import Lean4Lean.Theory.Typing.HeadReduction
import Lean4Lean.Theory.Inductive.Signature
import Lean4Lean.Theory.Inductive.CompilationLemmas
import Lean4Lean.Theory.Inductive.RecursiveShapeCorrespondence
